from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "Probability/LLM_Viki_Dataset/Chapter5_Knowledge"
SOURCE = ROOT / "Probability/Textbook/Chapters/PTE-Chapter5.pdf"

CREATED = datetime.now(timezone.utc).isoformat()


def piece(pid, section, title, kind, summary, proof_idea, exam_use, pitfalls, tags, related=None):
    return {
        "id": f"durrett_ch5_{pid}",
        "source": "Rick Durrett, Probability: Theory and Examples, extracted Chapter 5 PDF",
        "source_file": str(SOURCE),
        "chapter": 5,
        "section": section,
        "title": title,
        "kind": kind,
        "summary": summary,
        "proof_idea": proof_idea,
        "exam_use": exam_use,
        "pitfalls": pitfalls,
        "tags": tags,
        "related_ids": related or [],
        "created_at": CREATED,
    }


PIECES = [
    piece(
        "markov_property_countable",
        "5.1 Examples",
        "Countable-state Markov property",
        "definition",
        "A temporally homogeneous countable-state Markov chain satisfies P(X_{n+1}=j | X_n=i, past)=P(X_{n+1}=j | X_n=i)=p(i,j).",
        "The current state is a sufficient statistic for predicting the next state, so the transition matrix contains all one-step dynamics.",
        "Use this as the first diagnostic for deciding whether a proposed process is Markov and for computing transition probabilities.",
        "A function of a Markov chain need not be Markov unless the retained state contains enough information.",
        ["markov-property", "transition-matrix", "countable-state"],
    ),
    piece(
        "random_walk_chain",
        "5.1 Examples",
        "Random walk as a Markov chain",
        "example-pattern",
        "If X_n=X_0+xi_1+...+xi_n with iid increments on Z^d, then p(i,j)=mu({j-i}).",
        "Condition on X_n; the next state is obtained by adding the independent increment xi_{n+1}.",
        "Use whenever increments are independent and stationary; transition probabilities depend only on displacement.",
        "A random walk often has no finite equilibrium on infinite groups even though it is Markov.",
        ["random-walk", "increments", "translation-invariance"],
        ["durrett_ch5_markov_property_countable"],
    ),
    piece(
        "branching_process_chain",
        "5.1 Examples",
        "Branching process transition kernel",
        "example-pattern",
        "For a Galton-Watson process, p(i,j)=P(xi_1+...+xi_i=j), where each current individual independently produces offspring.",
        "Given X_n=i, the next generation is the sum of i iid offspring counts.",
        "Recognize absorbing extinction state 0 and use generating functions for transition calculations.",
        "The process is Markov in the population size, but it typically does not converge to a nontrivial equilibrium.",
        ["branching-process", "offspring", "absorbing-state"],
    ),
    piece(
        "ehrenfest_chain",
        "5.1 Examples",
        "Ehrenfest urn chain",
        "example-pattern",
        "With r balls and state k equal to the number in the first urn, p(k,k+1)=(r-k)/r and p(k,k-1)=k/r.",
        "One randomly selected ball changes urns, increasing or decreasing k according to which urn the ball came from.",
        "A canonical finite birth-death chain for reversibility, stationary distributions, and periodicity.",
        "The chain alternates parity, so convergence of p^n(k,j) must account for period 2 unless laziness is added.",
        ["ehrenfest", "birth-death", "finite-chain", "periodicity"],
    ),
    piece(
        "wright_fisher_chain",
        "5.1 Examples",
        "Wright-Fisher transition law",
        "example-pattern",
        "In a population of N genes, the number of A alleles has binomial transition p(i,j)=C(N,j) rho_i^j(1-rho_i)^{N-j}; without mutation rho_i=i/N, with mutation rho_i=(i/N)(1-u)+((N-i)/N)v.",
        "The next generation is sampled with replacement from the current generation, with mutation modifying the success probability.",
        "Use for absorption/fixation problems, martingale hitting probabilities, and finite-chain equilibrium with mutation.",
        "Without mutation, 0 and N are absorbing; with positive mutation rates they are not.",
        ["wright-fisher", "binomial-transition", "mutation", "absorption"],
    ),
    piece(
        "mg1_queue_chain",
        "5.1 Examples",
        "M/G/1 embedded queue chain",
        "example-pattern",
        "At service-start epochs, X_{n+1}=(X_n+xi_{n+1})^+, where P(xi=k-1)=a_k and a_k is the chance k arrivals occur during one service time.",
        "Between service starts, arrivals during the service time add customers while the served customer leaves; the positive part handles an empty queue.",
        "Use drift E xi=mean arrivals per service minus 1 to classify recurrence and stability.",
        "Do not confuse the continuous-time queue with the embedded discrete chain at service-start times.",
        ["queue", "mg1", "reflected-random-walk", "drift"],
    ),
    piece(
        "general_transition_probability",
        "5.2 Construction, Markov Properties",
        "General transition probability",
        "definition",
        "On a measurable state space, p(x,A) is a transition probability when A -> p(x,A) is a probability measure and x -> p(x,A) is measurable.",
        "The two requirements make integration over paths well-defined and allow conditioning on X_n.",
        "Use this language for chains beyond countable state spaces, including queues and continuous densities.",
        "For general spaces, p(x,y) is usually not a number; the kernel is p(x,A).",
        ["transition-kernel", "measurable-space", "general-state-space"],
    ),
    piece(
        "finite_dimensional_construction",
        "5.2 Construction, Markov Properties",
        "Finite-dimensional construction of a chain",
        "construction",
        "Given initial law mu and kernel p, the finite-dimensional laws are iterated integrals mu(dx_0)p(x_0,dx_1)...p(x_{n-1},dx_n).",
        "The consistency of these marginals lets the extension theorem create a path-space process.",
        "Justifies statements that a Markov chain with a specified initial distribution and transition kernel exists.",
        "The formula gives path probabilities only for measurable cylinder events, then extension supplies the full path law.",
        ["construction", "finite-dimensional-distributions", "path-space"],
        ["durrett_ch5_general_transition_probability"],
    ),
    piece(
        "expectation_operator_notation",
        "5.2 Construction, Markov Properties",
        "Transition operator notation",
        "notation",
        "For bounded measurable f, Pf(x)=E_x f(X_1)=integral f(y)p(x,dy); iterates P^n describe n-step expectations.",
        "Integrating one step at a time turns the transition kernel into a linear operator.",
        "Useful for harmonic equations, hitting probabilities, expected hitting times, and martingale checks.",
        "The same symbol p may denote a kernel or a matrix; P as an operator acts on functions.",
        ["transition-operator", "expectation", "harmonic-functions"],
    ),
    piece(
        "markov_property_shift",
        "5.2 Construction, Markov Properties",
        "Markov property with path shifts",
        "theorem",
        "For bounded future functionals Y, E_x[Y o theta_n | F_n]=E_{X_n}Y.",
        "Check cylinder future events, extend by a monotone-class argument, and use the construction formula.",
        "Transforms future-path questions after time n into a fresh chain started at X_n.",
        "The future functional must be evaluated on the shifted path; forgetting the shift changes the event.",
        ["markov-property", "shift-operator", "monotone-class"],
        ["durrett_ch5_finite_dimensional_construction"],
    ),
    piece(
        "chapman_kolmogorov",
        "5.2 Construction, Markov Properties",
        "Chapman-Kolmogorov equations",
        "theorem",
        "The n-step kernels satisfy p^{m+n}(x,z)=sum_y p^m(x,y)p^n(y,z) in countable spaces, with the analogous integral formula in general spaces.",
        "Condition on the state at the intermediate time m and apply the Markov property.",
        "Compute multi-step transitions, prove communication, and derive renewal decompositions for return probabilities.",
        "For general spaces, replace sums over y by integration against p^m(x,dy).",
        ["chapman-kolmogorov", "n-step-transition", "semigroup"],
        ["durrett_ch5_markov_property_shift"],
    ),
    piece(
        "strong_markov_property",
        "5.2 Construction, Markov Properties",
        "Strong Markov property",
        "theorem",
        "At a stopping time T, the post-T process behaves like a fresh chain started from X_T on the event T<infinity.",
        "Approximate the stopping time by its atoms {T=n}, apply the ordinary Markov property on each atom, and sum.",
        "The main engine for hitting-time decompositions, renewal arguments, recurrence proofs, and reflection arguments.",
        "T must be a stopping time; optional-looking random times that see the future do not qualify.",
        ["strong-markov", "stopping-time", "hitting-times"],
        ["durrett_ch5_markov_property_shift"],
    ),
    piece(
        "hitting_return_decomposition",
        "5.2 Construction, Markov Properties",
        "Hitting and return time decomposition",
        "proof-template",
        "Events involving visits to a state or set can be decomposed at the first hitting time and restarted by the strong Markov property.",
        "Split according to T_y=k or T_A=k, then apply the strong Markov property to the shifted future.",
        "Use for equations like P_x(T_z<infinity) >= P_x(T_y<infinity)P_y(T_z<infinity) and for first-step analysis.",
        "Use T_y=inf{n>=1:X_n=y} for returns and V_A=inf{n>=0:X_n in A} for entrance; the indexing matters.",
        ["hitting-time", "return-time", "first-step-analysis"],
        ["durrett_ch5_strong_markov_property"],
    ),
    piece(
        "reflection_principle",
        "5.2 Construction, Markov Properties",
        "Reflection principle for symmetric random walk",
        "theorem",
        "For one-dimensional simple symmetric random walk, paths crossing a level can be reflected after the first hitting time to convert maximum events into endpoint events.",
        "Stop at the first hit of the barrier and flip the signs of all later increments, giving a bijection of path sets.",
        "Fast route to distributions of maxima and hitting probabilities for simple random walk.",
        "The clean reflection bijection uses symmetry and nearest-neighbor increments; it does not transfer unchanged to arbitrary walks.",
        ["reflection-principle", "simple-random-walk", "maximum"],
        ["durrett_ch5_strong_markov_property"],
    ),
    piece(
        "recurrence_visit_criterion",
        "5.3 Recurrence and Transience",
        "Expected visits criterion",
        "theorem",
        "A state y is recurrent iff E_y N(y)=sum_n p^n(y,y)=infinity; if transient this expected visit count is finite.",
        "After each return to y, the strong Markov property restarts the process, so the number of returns has a geometric structure.",
        "Use Green-function sums to classify states, especially for random walks.",
        "The criterion is for visits starting from y; from another x, accessibility must be handled separately.",
        ["recurrence", "transience", "green-function", "return-count"],
        ["durrett_ch5_strong_markov_property"],
    ),
    piece(
        "communication_recurrence_transfer",
        "5.3 Recurrence and Transience",
        "Recurrence transfers through communication",
        "theorem",
        "If x is recurrent and rho_xy>0, then y is recurrent and rho_yx=1.",
        "A recurrent x is visited infinitely often; successful excursions from x to y eventually occur, and returning to x forces y to communicate back.",
        "Shows recurrence is a class property inside communicating classes.",
        "Accessibility in only one direction is not symmetric unless recurrence is known.",
        ["communication", "recurrence-class", "irreducibility"],
        ["durrett_ch5_recurrence_visit_criterion"],
    ),
    piece(
        "finite_closed_recurrent_class",
        "5.3 Recurrence and Transience",
        "Finite closed classes contain recurrent states",
        "theorem",
        "Every finite closed set contains a recurrent state; if the finite closed set is irreducible, all its states are recurrent.",
        "A chain trapped in a finite set must visit at least one state infinitely often, then recurrence transfers through communication.",
        "Use to classify finite Markov chains and prove absorbing/recurrent structure.",
        "The set must be closed; otherwise the chain can leave and never return.",
        ["finite-chain", "closed-class", "recurrence"],
        ["durrett_ch5_communication_recurrence_transfer"],
    ),
    piece(
        "decomposition_theorem",
        "5.3 Recurrence and Transience",
        "Decomposition theorem",
        "theorem",
        "The recurrent states split into disjoint irreducible closed classes, while every transient state is visited only finitely often almost surely.",
        "Use communication equivalence for recurrent states and the finite expected visits criterion for transients.",
        "Organizes the long-run behavior of countable chains before stationary distributions enter.",
        "Closed recurrent classes need not be finite; irreducibility is within each class, not necessarily the whole state space.",
        ["decomposition", "recurrent-classes", "transient-states"],
        ["durrett_ch5_recurrence_visit_criterion", "durrett_ch5_communication_recurrence_transfer"],
    ),
    piece(
        "foster_supermartingale_recurrence",
        "5.3 Recurrence and Transience",
        "Foster-type recurrence criterion",
        "criterion",
        "For an irreducible chain, a nonnegative function phi with E_x phi(X_1)<=phi(x) off a finite set and phi(x)->infinity can force recurrence.",
        "Stop phi(X_n) on leaving large finite regions and use optional-stopping/supermartingale estimates to prevent escape to infinity.",
        "A powerful recurrence test for birth-death chains, queues, and chains with inward drift.",
        "Check the direction of drift carefully; superharmonic behavior outside a finite set is the recurrence signal.",
        ["foster-criterion", "supermartingale", "lyapunov", "recurrence"],
    ),
    piece(
        "birth_death_scale_function",
        "5.3 Recurrence and Transience",
        "Birth-death scale function",
        "formula",
        "For a birth-death chain, harmonic scale functions solve p_x h(x+1)+q_x h(x-1)=h(x) and give explicit two-sided hitting probabilities.",
        "Rewrite the harmonic equation in first differences so ratios telescope as products q_i/p_i.",
        "Use for gambler's ruin probabilities and recurrence tests on {0,1,2,...}.",
        "Boundary conventions at 0 matter; write the model's p_0 and q_0 before applying formulas.",
        ["birth-death", "scale-function", "hitting-probability"],
    ),
    piece(
        "birth_death_recurrence_test",
        "5.3 Recurrence and Transience",
        "Birth-death recurrence test",
        "criterion",
        "For a birth-death chain on nonnegative integers, recurrence of 0 is determined by divergence of the scale sum built from products q_i/p_i.",
        "Let the upper boundary M tend to infinity in the two-sided hitting formula.",
        "High-yield test for nearest-neighbor chains with state-dependent drift.",
        "Small asymptotic drift terms such as C/j can decide the boundary between recurrence and transience.",
        ["birth-death", "recurrence-test", "scale-sum"],
        ["durrett_ch5_birth_death_scale_function"],
    ),
    piece(
        "random_walk_recurrent_values",
        "5.4 Recurrence of Random Walks Starred Section",
        "Recurrent values form a closed subgroup",
        "theorem",
        "For a random walk on R^d, the set of recurrent values is either empty or a closed subgroup of R^d.",
        "Use independence and translation invariance to show the set is closed under differences and limits.",
        "Clarifies what recurrence can mean outside lattice state spaces.",
        "Returning near a value is a topological notion in R^d, not necessarily exact equality.",
        ["random-walk", "recurrent-values", "closed-subgroup"],
    ),
    piece(
        "random_walk_recurrence_equivalences",
        "5.4 Recurrence of Random Walks Starred Section",
        "Equivalent random-walk recurrence criteria",
        "theorem",
        "For random walks, recurrence can be characterized by infinitely many visits to neighborhoods, divergence of occupation sums, and Green-function criteria.",
        "Relate neighborhood visits to the Markov property and use zero-one/renewal arguments.",
        "Choose the criterion that matches the data: local probabilities, characteristic functions, or limit theorems.",
        "The exact form differs between lattice and nonlattice settings; keep the state-space topology visible.",
        ["random-walk", "recurrence-criteria", "green-function"],
        ["durrett_ch5_recurrence_visit_criterion"],
    ),
    piece(
        "simple_random_walk_dimension",
        "5.4 Recurrence of Random Walks Starred Section",
        "Simple random walk recurrence by dimension",
        "theorem",
        "Simple random walk is recurrent in dimensions 1 and 2 and transient in dimensions 3 and higher.",
        "Estimate the return probabilities: they behave like n^{-d/2}, whose series diverges for d<=2 and converges for d>=3.",
        "A central classification result and a common comparison model for Markov-chain recurrence.",
        "Parity affects exact return times but not the convergence/divergence classification.",
        ["simple-random-walk", "dimension", "recurrence", "transience"],
        ["durrett_ch5_recurrence_visit_criterion"],
    ),
    piece(
        "chung_fuchs_one_dimension",
        "5.4 Recurrence of Random Walks Starred Section",
        "Chung-Fuchs one-dimensional recurrence pattern",
        "theorem",
        "In one dimension, centered weak-law behavior is the key condition behind recurrence for broad random walks.",
        "Use truncation and characteristic-function/Fourier criteria to control occupation near the origin.",
        "Use when increments are not nearest-neighbor but have no drift on the natural scale.",
        "Nonzero drift typically pushes the walk to infinity and destroys recurrence.",
        ["chung-fuchs", "one-dimensional-random-walk", "drift"],
    ),
    piece(
        "two_dimensional_normal_recurrence",
        "5.4 Recurrence of Random Walks Starred Section",
        "Two-dimensional normal-limit recurrence",
        "theorem",
        "A two-dimensional random walk with S_n/sqrt(n) converging to a nondegenerate normal law is recurrent.",
        "Use the local/weak normal approximation to show enough mass returns to fixed neighborhoods for the occupation sum to diverge.",
        "Recognize recurrence for centered finite-variance planar walks.",
        "A degenerate limiting covariance needs separate lower-dimensional analysis.",
        ["two-dimensional-random-walk", "normal-limit", "recurrence"],
    ),
    piece(
        "fourier_recurrence_criterion",
        "5.4 Recurrence of Random Walks Starred Section",
        "Fourier recurrence criterion",
        "criterion",
        "Random-walk recurrence can be tested through integrals involving 1/(1-phi(t)), where phi is the increment characteristic function.",
        "Parseval-type identities convert occupation sums into Fourier integrals over powers of phi.",
        "Useful for non-nearest-neighbor walks and for proving no truly three-dimensional walk is recurrent.",
        "The singularity near t=0 is decisive; away from zero the integral is usually harmless.",
        ["fourier", "characteristic-functions", "recurrence"],
    ),
    piece(
        "no_truly_three_dimensional_recurrence",
        "5.4 Recurrence of Random Walks Starred Section",
        "No truly three-dimensional recurrent random walk",
        "theorem",
        "A random walk with genuinely three-dimensional increment support cannot be recurrent.",
        "Near the origin, the Fourier denominator behaves too singularly in dimension 3 for recurrence-compatible divergence.",
        "Use as a broad transience result beyond simple random walk.",
        "If the walk actually lives in a lower-dimensional subgroup, reduce the dimension before applying the theorem.",
        ["three-dimensional", "random-walk", "transience", "fourier"],
        ["durrett_ch5_fourier_recurrence_criterion"],
    ),
    piece(
        "stationary_measure_definition",
        "5.5 Stationary Measures",
        "Stationary measures and distributions",
        "definition",
        "A measure mu is stationary when mu p=mu; if mu(S)=1 it is a stationary distribution.",
        "Stationarity says one transition step leaves the law unchanged.",
        "Find equilibria, normalize invariant measures, and connect long-run proportions to return times.",
        "An infinite stationary measure need not be a probability distribution and does not by itself imply equilibrium probabilities.",
        ["stationary-measure", "invariant-measure", "equilibrium"],
    ),
    piece(
        "reversibility_detailed_balance",
        "5.5 Stationary Measures",
        "Reversibility and detailed balance",
        "criterion",
        "If mu(x)p(x,y)=mu(y)p(y,x) for all x,y, then mu is stationary and the chain is reversible under mu.",
        "Sum the detailed-balance identity over x to get stationarity; path probabilities are unchanged by time reversal.",
        "The fastest way to find stationary distributions for birth-death, Ehrenfest, and many urn chains.",
        "Detailed balance is sufficient but not necessary for stationarity unless reversibility is required.",
        ["reversibility", "detailed-balance", "stationary-distribution"],
        ["durrett_ch5_stationary_measure_definition"],
    ),
    piece(
        "kolmogorov_cycle_condition",
        "5.5 Stationary Measures",
        "Kolmogorov cycle condition",
        "theorem",
        "For an irreducible chain, reversibility is characterized by equality of transition-probability products around every directed cycle and its reverse.",
        "Multiply detailed-balance equations around a cycle for necessity; construct ratios along paths for sufficiency.",
        "Use to test whether a proposed chain can be reversible without solving for pi first.",
        "The condition is about all cycles; checking only two-state moves can miss circulation.",
        ["kolmogorov-cycle", "reversibility", "cycles"],
        ["durrett_ch5_reversibility_detailed_balance"],
    ),
    piece(
        "stationary_measure_from_returns",
        "5.5 Stationary Measures",
        "Stationary measure from one recurrent cycle",
        "theorem",
        "If x is recurrent and T_x is the first positive return time, then expected occupation counts before T_x define a stationary measure with mass 1 at x.",
        "Use the strong Markov property to balance expected exits and entries over a regenerative cycle.",
        "Construct invariant measures for recurrent irreducible chains without guessing.",
        "The measure may have infinite total mass when the chain is null recurrent.",
        ["occupation-measure", "regeneration", "stationary-measure", "return-time"],
        ["durrett_ch5_strong_markov_property"],
    ),
    piece(
        "stationary_measure_uniqueness_recurrent",
        "5.5 Stationary Measures",
        "Uniqueness of stationary measure in irreducible recurrent chains",
        "theorem",
        "For an irreducible recurrent countable chain, the stationary measure is unique up to constant multiples.",
        "Compare any invariant measure with the regenerative occupation measure normalized at one state.",
        "Lets you identify all invariant measures once one candidate is found.",
        "Uniqueness up to scale does not mean a stationary distribution exists; total mass may be infinite.",
        ["irreducible", "recurrent", "stationary-measure", "uniqueness"],
        ["durrett_ch5_stationary_measure_from_returns"],
    ),
    piece(
        "positive_recurrence_return_time",
        "5.5 Stationary Measures",
        "Stationary probability and mean return time",
        "theorem",
        "For an irreducible chain with stationary distribution pi, pi(y)=1/E_y T_y, so states with finite mean return time are positive recurrent.",
        "Apply the regenerative stationary measure over one return cycle and normalize by its total expected length.",
        "Compute stationary probabilities through expected return times and classify positive versus null recurrence.",
        "Recurrence only says T_y is finite almost surely; positive recurrence requires finite expectation.",
        ["positive-recurrence", "mean-return-time", "stationary-distribution"],
        ["durrett_ch5_stationary_measure_from_returns"],
    ),
    piece(
        "positive_recurrence_equivalences",
        "5.5 Stationary Measures",
        "Positive recurrence equivalences",
        "theorem",
        "For an irreducible chain, existence of a stationary distribution, finite mean return times, and positive recurrence are equivalent.",
        "Normalize the recurrent-cycle stationary measure when its total mass is finite; conversely use stationarity to derive finite return times.",
        "A standard checklist for proving an irreducible chain has an equilibrium law.",
        "In infinite state spaces, irreducible recurrent chains can be null recurrent and fail to have a stationary distribution.",
        ["positive-recurrence", "stationary-distribution", "return-times"],
        ["durrett_ch5_positive_recurrence_return_time"],
    ),
    piece(
        "birth_death_stationary_distribution",
        "5.5 Stationary Measures",
        "Birth-death stationary distribution",
        "formula",
        "For birth-death chains, detailed balance gives pi(x) proportional to products of birth rates divided by death rates, if the normalizing sum is finite.",
        "Solve pi(x)p_x=pi(x+1)q_{x+1} recursively and normalize.",
        "Fast equilibrium computation for queues, Ehrenfest-type chains, and one-dimensional population models.",
        "The unnormalized weights may define an invariant measure even when their sum diverges.",
        ["birth-death", "stationary-distribution", "detailed-balance"],
        ["durrett_ch5_reversibility_detailed_balance"],
    ),
    piece(
        "mg1_stability_stationarity",
        "5.5 Stationary Measures",
        "M/G/1 stability and stationarity",
        "example-pattern",
        "For the embedded M/G/1 queue, stability/positive recurrence occurs when the mean number of arrivals during one service time is less than 1.",
        "Compare the reflected queue length to a random walk with drift E xi=mu-1 and use recurrence/return-time arguments.",
        "Use drift less than zero as the queue stability condition.",
        "Recurrence and stationary behavior fail at or above critical load in different ways; do not treat mu=1 as stable.",
        ["mg1", "queue-stability", "positive-recurrence", "drift"],
        ["durrett_ch5_mg1_queue_chain", "durrett_ch5_positive_recurrence_equivalences"],
    ),
    piece(
        "renewal_limit_return_probabilities",
        "5.6 Asymptotic Behavior",
        "Renewal limit for return probabilities",
        "theorem",
        "If y is recurrent, then p^n(y,y) has asymptotics governed by the renewal theorem for the return-time distribution; positive recurrence gives limits tied to 1/E_y T_y.",
        "Decompose visits to y into renewals generated by successive return times.",
        "Explains why return-time periods and mean cycle lengths control long-run transition probabilities.",
        "Periodicity can force p^n(y,y)=0 on many n, so limits may only exist along arithmetic subsequences.",
        ["renewal-theorem", "return-probabilities", "asymptotics"],
        ["durrett_ch5_positive_recurrence_return_time"],
    ),
    piece(
        "period_definition",
        "5.6 Asymptotic Behavior",
        "Period of a state",
        "definition",
        "The period of state x is the greatest common divisor of {n>=1:p^n(x,x)>0}; irreducible communicating states share the same period.",
        "Use concatenation of paths and communication to transfer possible return-time arithmetic between states.",
        "Check whether convergence to stationarity can hold at every time or only along residue classes.",
        "A chain can be irreducible and positive recurrent but still fail ordinary convergence because of period greater than 1.",
        ["periodicity", "aperiodic", "irreducibility"],
    ),
    piece(
        "aperiodic_convergence_theorem",
        "5.6 Asymptotic Behavior",
        "Aperiodic convergence theorem",
        "theorem",
        "If a countable chain is irreducible, aperiodic, and has stationary distribution pi, then p^n(x,y) -> pi(y).",
        "Couple two independent chains through the product chain and show they meet with probability tending to one.",
        "Main equilibrium convergence theorem for prelim Markov-chain problems.",
        "Irreducible and stationary are not enough; without aperiodicity the raw n-step probabilities may oscillate.",
        ["convergence-to-stationarity", "aperiodic", "coupling", "positive-recurrence"],
        ["durrett_ch5_period_definition", "durrett_ch5_positive_recurrence_equivalences"],
    ),
    piece(
        "coupling_for_finite_chains",
        "5.6 Asymptotic Behavior",
        "Coupling bound for convergence",
        "proof-template",
        "If two copies of a Markov chain are run together after meeting, then total variation distance is bounded by the probability their coupling time exceeds n.",
        "Construct the product chain, make the two coordinates coalesce at the diagonal, and compare events before and after meeting.",
        "Use for finite irreducible aperiodic chains and for quantitative convergence estimates.",
        "The coupling must preserve the correct marginal transition law for each coordinate.",
        ["coupling", "total-variation", "mixing"],
        ["durrett_ch5_aperiodic_convergence_theorem"],
    ),
    piece(
        "additive_functional_lln",
        "5.6 Asymptotic Behavior",
        "Strong law for additive functionals",
        "theorem",
        "For an irreducible positive recurrent chain with stationary law pi, time averages of suitable f(X_n) converge to sum_x pi(x)f(x).",
        "Break the path into regenerative cycles between visits to a reference state and apply iid cycle laws.",
        "Use to turn long-run sample averages into stationary expectations.",
        "Integrability under pi is essential; positive recurrence alone does not control arbitrary unbounded rewards.",
        ["ergodic-theorem", "additive-functional", "time-average"],
        ["durrett_ch5_positive_recurrence_equivalences"],
    ),
    piece(
        "periodic_convergence_classes",
        "5.7 Periodicity, Tail Sigma-Field Starred Section",
        "Periodic cyclic classes",
        "theorem",
        "For an irreducible recurrent chain of period d, the state space splits into d cyclic classes and the d-step chain on each class is aperiodic.",
        "Group states according to hitting-time residues modulo d and use the gcd definition of period.",
        "Use to repair convergence statements for periodic chains by passing to subsequences n congruent to r mod d.",
        "The stationary distribution is still a distribution on all states, but mass is visited cyclically rather than approached at all times.",
        ["periodicity", "cyclic-classes", "periodic-convergence"],
        ["durrett_ch5_period_definition"],
    ),
    piece(
        "periodic_convergence_theorem",
        "5.7 Periodicity, Tail Sigma-Field Starred Section",
        "Periodic convergence theorem",
        "theorem",
        "For irreducible positive recurrent chains with period d, p^n(x,y) converges along the compatible residue class to d*pi(y) and is zero on incompatible residues.",
        "Apply the aperiodic convergence theorem to the d-step chain on the cyclic class containing y.",
        "Use when examples such as simple random walk on bipartite graphs oscillate forever.",
        "The factor d appears because the d-step chain's stationary law is pi restricted to one cyclic class and renormalized.",
        ["periodic-convergence", "cyclic-classes", "stationary-distribution"],
        ["durrett_ch5_periodic_convergence_classes", "durrett_ch5_aperiodic_convergence_theorem"],
    ),
    piece(
        "tail_sigma_field_triviality_pattern",
        "5.7 Periodicity, Tail Sigma-Field Starred Section",
        "Tail sigma-field triviality via coupling",
        "proof-template",
        "For suitable irreducible recurrent chains, tail events have probability 0 or 1 because coupled copies eventually share the same future behavior.",
        "Represent two copies, couple them after a meeting or cyclic alignment, and observe that tail events are unchanged by finite initial segments.",
        "Use for zero-one laws about eventual behavior of recurrent Markov chains and simple random walk.",
        "Tail events are not the same as invariant events at a fixed time; they ignore every finite prefix.",
        ["tail-sigma-field", "zero-one-law", "coupling"],
    ),
    piece(
        "harris_recurrence",
        "5.8 General State Space Starred Section",
        "Harris recurrence",
        "definition",
        "A general-state Markov chain is Harris recurrent when it repeatedly hits every set of positive reference measure from relevant starting points.",
        "A reference measure replaces countable-state point accessibility, letting recurrence be stated for measurable sets.",
        "Use as the general-state analogue of irreducible recurrence.",
        "In continuous spaces, single points often have probability zero, so point-return definitions are too strong or meaningless.",
        ["harris-recurrence", "general-state-space", "reference-measure"],
        ["durrett_ch5_general_transition_probability"],
    ),
    piece(
        "small_set_split_chain",
        "5.8 General State Space Starred Section",
        "Small sets and split-chain idea",
        "construction",
        "A small set has a minorization that lets one split transitions into regeneration attempts and residual motion.",
        "Use the minorization to add an artificial atom, reducing parts of the general-state chain to countable-style regeneration.",
        "The conceptual bridge from countable recurrent-chain proofs to Harris-chain stationary and convergence theorems.",
        "Minorization is a structural condition; it is not just positive probability of hitting a set.",
        ["small-set", "minorization", "split-chain", "regeneration"],
        ["durrett_ch5_harris_recurrence"],
    ),
    piece(
        "harris_stationary_measure",
        "5.8 General State Space Starred Section",
        "Stationary measure for recurrent Harris chains",
        "theorem",
        "In the recurrent Harris setting, there is a sigma-finite stationary measure, and it is unique up to scale under the appropriate irreducibility assumptions.",
        "Construct a regenerative stationary measure using the split chain and then project back to the original chain.",
        "Generalizes countable-state invariant-measure construction to continuous state spaces.",
        "Sigma-finite stationary measure is not automatically a stationary distribution; total mass decides positive recurrence.",
        ["harris-chain", "stationary-measure", "sigma-finite", "regeneration"],
        ["durrett_ch5_small_set_split_chain", "durrett_ch5_stationary_measure_from_returns"],
    ),
    piece(
        "harris_convergence_theorem",
        "5.8 General State Space Starred Section",
        "Aperiodic Harris convergence theorem",
        "theorem",
        "An aperiodic positive recurrent Harris chain with stationary distribution converges to that stationary distribution in total variation from suitable starting laws.",
        "Use split-chain regeneration and coupling, paralleling the countable-state aperiodic convergence proof.",
        "Use for continuous-state Markov models where transition densities make pointwise matrix methods unavailable.",
        "The theorem requires Harris recurrence and aperiodicity; a stationary density alone may not give convergence from every start.",
        ["harris-chain", "total-variation", "convergence", "aperiodic"],
        ["durrett_ch5_harris_stationary_measure", "durrett_ch5_aperiodic_convergence_theorem"],
    ),
    piece(
        "gig1_queue_storage_model",
        "5.8 General State Space Starred Section",
        "GI/G/1 queue as a reflected random walk",
        "example-pattern",
        "The waiting-time recursion W_{n+1}=(W_n+eta_n-zeta_n)^+ is a general-state Markov chain and storage model.",
        "Service requirements add workload and interarrival times subtract available service time, with reflection at zero.",
        "Use drift E eta < E zeta for stability and Harris-chain tools for stationary waiting-time distributions.",
        "The embedded workload is continuous-state, so countable transition-matrix formulas do not apply directly.",
        ["gig1", "storage-model", "reflected-random-walk", "harris-chain"],
        ["durrett_ch5_harris_convergence_theorem"],
    ),
]


SECTION_GUIDES = [
    {
        "section": "5.1 Examples",
        "study_goal": "Recognize Markov structure in standard models and compute their transition probabilities.",
        "must_master": ["Markov property", "transition matrix", "random walk", "branching process", "Ehrenfest", "Wright-Fisher", "M/G/1 queue"],
        "prelim_angle": "Many exam problems start by asking whether a process is Markov and what its transition law is.",
    },
    {
        "section": "5.2 Construction, Markov Properties",
        "study_goal": "Use kernels, path-space construction, Markov property, Chapman-Kolmogorov, and strong Markov property.",
        "must_master": ["transition kernels", "finite-dimensional distributions", "shifted Markov property", "Chapman-Kolmogorov", "strong Markov property", "hitting times"],
        "prelim_angle": "Strong Markov arguments power almost every hitting-time and recurrence calculation.",
    },
    {
        "section": "5.3 Recurrence and Transience",
        "study_goal": "Classify states and classes using visits, communication, closed classes, and Lyapunov/scale tools.",
        "must_master": ["recurrent vs transient", "communication classes", "decomposition theorem", "Foster criterion", "birth-death scale functions"],
        "prelim_angle": "Expect problems asking whether a chain returns, escapes, or has recurrent classes.",
    },
    {
        "section": "5.4 Recurrence of Random Walks Starred Section",
        "study_goal": "Understand dimension-dependent random-walk recurrence through Green functions, limits, and Fourier criteria.",
        "must_master": ["Green-function sums", "simple random walk by dimension", "Chung-Fuchs", "Fourier recurrence tests"],
        "prelim_angle": "The d<=2 versus d>=3 classification is very high-yield, even if the starred Fourier details are less tested.",
    },
    {
        "section": "5.5 Stationary Measures",
        "study_goal": "Construct and identify invariant measures, stationary distributions, reversibility, and positive recurrence.",
        "must_master": ["stationary measure", "detailed balance", "cycle condition", "return-cycle occupation measure", "positive recurrence", "mean return time"],
        "prelim_angle": "Equilibrium computations usually reduce to detailed balance, normalization, or mean return times.",
    },
    {
        "section": "5.6 Asymptotic Behavior",
        "study_goal": "Connect recurrence and stationarity to long-run transition probabilities and ergodic averages.",
        "must_master": ["renewal limits", "period", "aperiodic convergence", "coupling", "additive functional LLN"],
        "prelim_angle": "Use irreducible + positive recurrent + aperiodic as the main convergence-to-stationarity checklist.",
    },
    {
        "section": "5.7 Periodicity, Tail Sigma-Field Starred Section",
        "study_goal": "Handle periodic chains by cyclic classes and understand tail-event zero-one behavior.",
        "must_master": ["cyclic classes", "periodic convergence", "tail sigma-field", "coupling zero-one arguments"],
        "prelim_angle": "Periodicity is the standard hidden reason a stationary chain does not have ordinary p^n convergence.",
    },
    {
        "section": "5.8 General State Space Starred Section",
        "study_goal": "Translate countable-state recurrence, stationarity, and convergence to Harris chains.",
        "must_master": ["Harris recurrence", "small sets", "split chain", "sigma-finite invariant measure", "Harris convergence", "GI/G/1 queue"],
        "prelim_angle": "Useful for advanced problems with continuous state spaces or queueing recursions.",
    },
]


def write_jsonl(path: Path, rows):
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def main():
    OUT.mkdir(parents=True, exist_ok=True)

    write_jsonl(OUT / "chapter5_knowledge_pieces.jsonl", PIECES)
    write_jsonl(OUT / "chapter5_section_guides.jsonl", SECTION_GUIDES)

    manifest = {
        "name": "durrett_chapter5_markov_chains_llm_viki",
        "description": "Curated LLM/Viki-style knowledge pieces for Chapter 5 of Durrett Probability: Theory and Examples.",
        "source_file": str(SOURCE),
        "created_at": CREATED,
        "piece_count": len(PIECES),
        "section_count": len(SECTION_GUIDES),
        "files": [
            "chapter5_knowledge_pieces.jsonl",
            "chapter5_section_guides.jsonl",
            "chapter5_viki.md",
            "chapter5_flashcards.tsv",
            "manifest.json",
        ],
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    md = ["# Durrett Chapter 5 LLM Viki: Markov Chains\n"]
    md.append("Source: local extracted PDF `Probability/Textbook/Chapters/PTE-Chapter5.pdf`.\n")
    md.append("These are curated study/LLM retrieval pieces, not verbatim textbook notes.\n")
    md.append("## Section Guides\n")
    for guide in SECTION_GUIDES:
        md.append(f"### {guide['section']}\n")
        md.append(f"- Goal: {guide['study_goal']}\n")
        md.append(f"- Must master: {', '.join(guide['must_master'])}\n")
        md.append(f"- Prelim angle: {guide['prelim_angle']}\n")
    md.append("## Knowledge Pieces\n")
    for item in PIECES:
        md.append(f"### {item['title']}\n")
        md.append(f"- ID: `{item['id']}`\n")
        md.append(f"- Section: {item['section']}\n")
        md.append(f"- Kind: {item['kind']}\n")
        md.append(f"- Summary: {item['summary']}\n")
        md.append(f"- Proof idea: {item['proof_idea']}\n")
        md.append(f"- Exam use: {item['exam_use']}\n")
        md.append(f"- Pitfall: {item['pitfalls']}\n")
        md.append(f"- Tags: {', '.join(item['tags'])}\n")
    (OUT / "chapter5_viki.md").write_text("\n".join(md), encoding="utf-8")

    flash = ["id\tfront\tback\ttags"]
    for item in PIECES:
        front = f"{item['title']} ({item['section']})"
        back = f"{item['summary']} Exam use: {item['exam_use']} Pitfall: {item['pitfalls']}"
        flash.append(f"{item['id']}\t{front}\t{back}\t{','.join(item['tags'])}")
    (OUT / "chapter5_flashcards.tsv").write_text("\n".join(flash) + "\n", encoding="utf-8")

    print(json.dumps(manifest, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
