from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "Probability/LLM_Viki_Dataset/Chapter7_Knowledge"
SOURCE = ROOT / "Probability/Textbook/Chapters/PTE-Chapter7.pdf"

CREATED = datetime.now(timezone.utc).isoformat()


def piece(pid, section, title, kind, summary, proof_idea, exam_use, pitfalls, tags, related=None):
    return {
        "id": f"durrett_ch7_{pid}",
        "source": "Rick Durrett, Probability: Theory and Examples, extracted Chapter 7 PDF",
        "source_file": str(SOURCE),
        "chapter": 7,
        "section": section,
        "title": title,
        "kind": kind,
        "summary": summary,
        "proof_idea": proof_idea,
        "exam_use": exam_use,
        "pitfalls": pitfalls,
        "tags": tags,
        "related_ids": related or [],
        "created_at": CREATED,
    }


PIECES = [
    piece(
        "brownian_definition",
        "7.1 Definition and Construction",
        "Brownian motion definition",
        "definition",
        "A Brownian motion has independent increments, Gaussian increments B(s+t)-B(s) with mean 0 and variance t, and almost surely continuous sample paths.",
        "The definition encodes CLT scaling for small displacements while adding continuity to rule out arbitrary versions with the same finite-dimensional laws.",
        "Use as the base checklist whenever a process is claimed to be Brownian.",
        "Independent Gaussian increments alone do not automatically give continuous paths unless a continuous modification is specified.",
        ["brownian-motion", "gaussian-increments", "continuous-paths"],
    ),
    piece(
        "translation_invariance",
        "7.1 Definition and Construction",
        "Translation invariance of increments",
        "fact",
        "The process {B_t-B_0:t>=0} is independent of B_0 and has the law of Brownian motion started at 0.",
        "Use independence of the initial value and subsequent increments, then extend from finite-dimensional cylinder events by a pi-lambda argument.",
        "Lets hitting and exit calculations reduce to a Brownian motion started at 0 or at the current location.",
        "This is spatial translation of the starting point, not time-shift Markov conditioning.",
        ["translation-invariance", "increments", "starting-point"],
    ),
    piece(
        "brownian_scaling",
        "7.1 Definition and Construction",
        "Brownian scaling",
        "formula",
        "For c>0 and B_0=0, {B_{cs}:s>=0} has the same finite-dimensional distributions as {sqrt(c) B_s:s>=0}.",
        "Check the one-dimensional normal variance and then use independent increments for all finite-dimensional distributions.",
        "High-yield tool for hitting-time laws, path regularity, and rescaling exit probabilities.",
        "Scaling changes time by c and space by sqrt(c); reversing these powers is a common error.",
        ["scaling", "self-similarity", "finite-dimensional-distributions"],
    ),
    piece(
        "gaussian_process_characterization",
        "7.1 Definition and Construction",
        "Gaussian process characterization",
        "theorem",
        "A continuous Gaussian process with mean 0 and covariance E[B_s B_t]=s wedge t is Brownian motion started at 0.",
        "The covariance matrix determines all finite-dimensional Gaussian laws and matches the independent-increment construction.",
        "Use to prove transformed processes are Brownian, especially time inversion.",
        "The covariance condition alone is not enough without the Gaussian finite-dimensional law and continuity.",
        ["gaussian-process", "covariance", "characterization"],
    ),
    piece(
        "kolmogorov_extension_construction",
        "7.1 Definition and Construction",
        "Kolmogorov extension construction",
        "construction",
        "Brownian finite-dimensional distributions are built from Gaussian transition densities and then extended consistently to a path-space probability law.",
        "Verify consistency of the transition-density integrals and apply Kolmogorov extension; then move to continuous paths through a modification/extension argument.",
        "Explains why the formal process exists before path properties are studied.",
        "The raw product path space can make continuity nonmeasurable; the continuous-path space fixes the measurable model.",
        ["construction", "kolmogorov-extension", "transition-density"],
    ),
    piece(
        "kolmogorov_continuity_criterion",
        "7.1 Definition and Construction",
        "Kolmogorov continuity criterion",
        "theorem",
        "If E|X_t-X_s|^beta <= K|t-s|^{1+alpha}, then dyadic paths admit a Holder-continuous version of any exponent gamma<alpha/beta.",
        "Control dyadic increments by Chebyshev and Borel-Cantelli, then chain dyadic intervals to bound arbitrary dyadic pairs.",
        "Use moment bounds to prove sample-path continuity for Gaussian and process constructions.",
        "The exponent comes from alpha/beta, not beta/alpha; endpoint exponents are usually not obtained.",
        ["kolmogorov-continuity", "holder", "borel-cantelli"],
    ),
    piece(
        "brownian_holder_half",
        "7.1 Definition and Construction",
        "Brownian Holder continuity below one half",
        "theorem",
        "Brownian paths are almost surely Holder continuous on compact intervals for every exponent gamma<1/2.",
        "Use Gaussian even moments E|B_t-B_s|^{2m}=C_m|t-s|^m in the Kolmogorov criterion and let m grow.",
        "Useful for justifying pathwise approximations while remembering Brownian paths are rough.",
        "The exponent 1/2 itself is not included.",
        ["holder", "path-regularity", "gaussian-moments"],
        ["durrett_ch7_kolmogorov_continuity_criterion"],
    ),
    piece(
        "brownian_nowhere_differentiable",
        "7.1 Definition and Construction",
        "Brownian paths are nowhere differentiable",
        "theorem",
        "With probability one, Brownian paths are not Lipschitz continuous, and hence not differentiable, at any time.",
        "If a path were locally Lipschitz, several nearby small increments would all be tiny; Gaussian small-ball estimates make this probability vanish after covering.",
        "Prevents calculus-style manipulation of B_t and motivates quadratic variation and Ito calculus.",
        "Continuity does not imply bounded variation or differentiability; Brownian paths are continuous but very rough.",
        ["nondifferentiability", "rough-paths", "path-regularity"],
        ["durrett_ch7_brownian_holder_half"],
    ),
    piece(
        "quadratic_variation_hint",
        "7.1 Definition and Construction",
        "Dyadic quadratic variation",
        "fact",
        "Along dyadic partitions of [0,t], the sum of squared Brownian increments converges to t in the sense used later for Ito's formula.",
        "Independence and Gaussian fourth-moment estimates show the mean is t and the variance of the sum goes to 0.",
        "Core intuition behind the extra (1/2)f'' term in Ito's formula.",
        "This is about squared increments; ordinary total variation behaves very differently.",
        ["quadratic-variation", "dyadic-partitions", "ito"],
    ),
    piece(
        "d_dimensional_brownian",
        "7.1 Definition and Construction",
        "Multidimensional Brownian motion",
        "definition",
        "A d-dimensional Brownian motion has independent one-dimensional Brownian coordinates and Gaussian transition density (2 pi t)^(-d/2) exp(-|y-x|^2/(2t)).",
        "Independence of coordinates factors the finite-dimensional distributions and gives the Euclidean Gaussian kernel.",
        "Use for vector Ito formulas and multidimensional hitting or transition-density computations.",
        "Do not replace coordinate independence by merely matching each marginal coordinate law.",
        ["multidimensional", "transition-density", "gaussian-kernel"],
    ),
    piece(
        "markov_property",
        "7.2 Markov Property, Blumenthal's 0-1 Law",
        "Brownian Markov property",
        "theorem",
        "Conditioned on the present, the shifted future of Brownian motion has the law of Brownian motion started from the current state and is independent of the past.",
        "Prove first for bounded cylinder functions of the future using Gaussian transition densities, then extend by the monotone class theorem.",
        "Use to restart Brownian motion at deterministic times and compute conditional expectations.",
        "The conditioning sigma-field is the completed right-continuous past; using an informal past can hide null-set issues.",
        ["markov-property", "conditional-expectation", "shift"],
    ),
    piece(
        "germ_field_equivalence",
        "7.2 Markov Property, Blumenthal's 0-1 Law",
        "Right-continuous germ conditioning",
        "technical-fact",
        "For bounded path functionals, conditioning on F_s^+ agrees almost surely with conditioning on the raw past F_s^0.",
        "Approximate functionals by finite-dimensional ones and use the Markov property plus right-continuity of Brownian paths.",
        "Clarifies why immediate-future events can be handled cleanly at time 0.",
        "This is an almost-sure equality of conditional expectations, not equality of all raw sigma-fields literally.",
        ["germ-field", "right-continuity", "conditioning"],
    ),
    piece(
        "blumenthal_zero_one",
        "7.2 Markov Property, Blumenthal's 0-1 Law",
        "Blumenthal's 0-1 law",
        "theorem",
        "Every event in the Brownian germ sigma-field F_0^+ has probability 0 or 1 under a fixed starting point.",
        "Condition the event on the raw time-zero sigma-field, which is trivial once the starting point is fixed.",
        "Use for immediate hitting, local oscillation, and path behavior as t downarrow 0.",
        "The probability may depend on the starting point; the law is not automatically uniform in x.",
        ["zero-one-law", "germ-field", "local-behavior"],
    ),
    piece(
        "immediate_positive_negative_hits",
        "7.2 Markov Property, Blumenthal's 0-1 Law",
        "Immediate crossing at the origin",
        "theorem",
        "Starting from 0, Brownian motion hits (0,infinity), hits (-infinity,0), and returns to 0 immediately with probability one.",
        "Each event has positive probability at arbitrarily small times by normal symmetry; Blumenthal's law upgrades positive probability to probability one.",
        "Useful when proving the zero set has no isolated points and when reasoning about local extrema.",
        "The return time is inf{t>0:B_t=0}; allowing t=0 would make the statement trivial.",
        ["immediate-hitting", "zero-set", "blumenthal"],
        ["durrett_ch7_blumenthal_zero_one"],
    ),
    piece(
        "time_inversion",
        "7.2 Markov Property, Blumenthal's 0-1 Law",
        "Brownian time inversion",
        "theorem",
        "If B starts at 0, then X_0=0 and X_t=t B_{1/t} for t>0 is again Brownian motion.",
        "Check Gaussian finite-dimensional distributions and covariance, then prove continuity at 0 from B_u/u -> 0 as u -> infinity.",
        "Transfers small-time Brownian statements into large-time statements.",
        "The transform is t B_{1/t}, not B_{1/t}/t.",
        ["time-inversion", "gaussian-characterization", "large-time"],
        ["durrett_ch7_gaussian_process_characterization"],
    ),
    piece(
        "brownian_tail_zero_one",
        "7.2 Markov Property, Blumenthal's 0-1 Law",
        "Brownian tail 0-1 law",
        "theorem",
        "Events determined by the arbitrarily far future have probability identically 0 or identically 1 for all starting states.",
        "Time inversion turns a tail event into a germ event; the Markov property removes dependence on the starting point.",
        "Use for recurrence and unbounded oscillation at infinity.",
        "This is stronger than the germ law because the conclusion is uniform in the starting state.",
        ["tail-sigma-field", "zero-one-law", "time-inversion"],
        ["durrett_ch7_time_inversion", "durrett_ch7_blumenthal_zero_one"],
    ),
    piece(
        "limsup_liminf_unbounded",
        "7.2 Markov Property, Blumenthal's 0-1 Law",
        "Large-time oscillation",
        "theorem",
        "One-dimensional Brownian motion satisfies limsup B_t/sqrt(t)=infinity and liminf B_t/sqrt(t)=-infinity almost surely.",
        "Discrete times have positive probability of exceeding any fixed multiple of sqrt(n) infinitely often; the tail 0-1 law upgrades this to probability one.",
        "Quick route to recurrence and repeated level-crossing arguments.",
        "This is weaker than the law of the iterated logarithm but enough for recurrence.",
        ["oscillation", "tail-zero-one", "recurrence"],
        ["durrett_ch7_brownian_tail_zero_one"],
    ),
    piece(
        "one_dimensional_recurrence",
        "7.2 Markov Property, Blumenthal's 0-1 Law",
        "One-dimensional Brownian recurrence",
        "theorem",
        "For every starting point, one-dimensional Brownian motion hits 0 infinitely often at arbitrarily large times almost surely.",
        "Large positive and negative oscillations plus path continuity force repeated crossings of 0.",
        "Use whenever hitting times of points are assumed finite or when restarting at returns.",
        "Recurrence in one dimension does not generalize unchanged to higher-dimensional hitting of points.",
        ["recurrence", "hitting", "one-dimensional"],
        ["durrett_ch7_limsup_liminf_unbounded"],
    ),
    piece(
        "stopping_time_definition",
        "7.3 Stopping Times, Strong Markov Property",
        "Stopping time definition",
        "definition",
        "A random time S is a stopping time when {S<t} is in F_t for every t; for right-continuous filtrations this is equivalent to using {S<=t}.",
        "The equivalence follows by countable unions/intersections and right-continuity of the filtration.",
        "Use to verify that hitting, exit, minima, and approximating times are legitimate restart times.",
        "The definition is about information available by time t, not about whether S has a density or finite expectation.",
        ["stopping-times", "filtration", "right-continuity"],
    ),
    piece(
        "hitting_times_open_closed",
        "7.3 Stopping Times, Strong Markov Property",
        "Open and closed hitting times are stopping times",
        "theorem",
        "For continuous Brownian paths, the first hitting time of an open set or a closed set is a stopping time.",
        "Open sets use rational times before t; closed sets are obtained as increasing limits of hitting times of shrinking open neighborhoods.",
        "Use to justify applying strong Markov property to level hitting and interval exit times.",
        "For general Borel sets the statement is true but much harder; do not use the open/closed proof blindly.",
        ["hitting-times", "open-sets", "closed-sets"],
        ["durrett_ch7_stopping_time_definition"],
    ),
    piece(
        "stopping_time_limits",
        "7.3 Stopping Times, Strong Markov Property",
        "Limits of stopping times",
        "closure-property",
        "Increasing and decreasing limits of stopping times are stopping times in a right-continuous filtration.",
        "Write events for the limiting time as countable unions or intersections of the corresponding events for the approximating times.",
        "Useful for proving complicated first-entry times by approximation.",
        "Right-continuity matters for some <= formulations.",
        ["stopping-times", "limits", "approximation"],
    ),
    piece(
        "random_shift_and_F_S",
        "7.3 Stopping Times, Strong Markov Property",
        "Random shift and information at a stopping time",
        "definition",
        "The shift theta_S removes the path before S and restarts time at S; F_S contains events whose restriction to {S<=t} is F_t-measurable for every t.",
        "These definitions formalize what is known at a random time and how to view the post-S path.",
        "Needed to state the strong Markov property and optional stopping cleanly.",
        "F_S is not simply F_t with t replaced by a random variable; it has its own measurability definition.",
        ["random-shift", "stopped-sigma-field", "strong-markov"],
    ),
    piece(
        "B_S_measurable",
        "7.3 Stopping Times, Strong Markov Property",
        "Stopped value is known at the stopping time",
        "theorem",
        "If S is a stopping time, then B_S is F_S-measurable.",
        "Approximate S from above by dyadic stopping times, note each approximating value is measurable at the approximating time, and pass to the limit by path continuity.",
        "Lets conditional expectations at stopping times depend on the random current position B_S.",
        "This uses continuity and the completed/right-continuous filtration setup.",
        ["stopped-process", "measurability", "dyadic-approximation"],
    ),
    piece(
        "strong_markov_property",
        "7.3 Stopping Times, Strong Markov Property",
        "Strong Markov property",
        "theorem",
        "Given a stopping time S, the post-S Brownian path conditioned on F_S has the law of Brownian motion started at B_S, on {S<infinity}.",
        "First prove it for discrete-valued stopping times, approximate a general S from above by dyadic stopping times, then extend by monotone class.",
        "The central engine for reflection principle, hitting-time increments, recurrence refinements, and exit calculations.",
        "Always check S is a stopping time and restrict or control the event {S<infinity}.",
        ["strong-markov", "stopping-times", "restart"],
        ["durrett_ch7_random_shift_and_F_S", "durrett_ch7_B_S_measurable"],
    ),
    piece(
        "zero_set_structure",
        "7.4 Path Properties",
        "Brownian zero set structure",
        "fact",
        "The zero set of one-dimensional Brownian motion is almost surely closed, has no isolated points, is uncountable, and has Lebesgue measure zero.",
        "Continuity gives closedness; recurrence plus immediate return and strong Markov give no isolated zeros; Fubini gives zero Lebesgue measure.",
        "Good conceptual anchor for path-property problems involving returns to zero.",
        "Uncountable does not imply positive Lebesgue measure.",
        ["zero-set", "perfect-set", "measure-zero"],
        ["durrett_ch7_immediate_positive_negative_hits", "durrett_ch7_strong_markov_property"],
    ),
    piece(
        "hitting_time_subordinator",
        "7.4 Path Properties",
        "Level hitting times have stationary independent increments",
        "theorem",
        "Under P_0, the process {T_a:a>=0}, where T_a=inf{t:B_t=a}, has stationary independent increments as a function of the level a.",
        "After hitting level a, the strong Markov property and translation invariance identify T_b-T_a with a fresh copy of T_{b-a}.",
        "Use to recognize hitting times as a stable subordinator of index 1/2.",
        "The parameter is the spatial level a, not the Brownian time parameter.",
        ["hitting-times", "subordinator", "stationary-independent-increments"],
        ["durrett_ch7_strong_markov_property", "durrett_ch7_translation_invariance"],
    ),
    piece(
        "hitting_time_scaling",
        "7.4 Path Properties",
        "Hitting-time scaling",
        "formula",
        "For a>0, T_a has the same distribution as a^2 T_1.",
        "Apply Brownian scaling: hitting a in the original process corresponds to hitting 1 after rescaling space by a and time by a^2.",
        "Quickly reduces level-dependent hitting-time questions to the case a=1.",
        "The square on a is essential; hitting times scale like distance squared.",
        ["hitting-times", "scaling", "stable-law"],
        ["durrett_ch7_brownian_scaling"],
    ),
    piece(
        "hitting_time_laplace_shape",
        "7.4 Path Properties",
        "Hitting-time Laplace transform shape",
        "formula",
        "The Laplace transform phi_a(lambda)=E_0 exp(-lambda T_a) has the exponential form exp(-a c(lambda)), and eventually c(lambda)=sqrt(2 lambda).",
        "Stationary independent increments give multiplicativity in the level; scaling forces c(lambda) to be proportional to sqrt(lambda).",
        "Use before or after exponential martingales to compute exact transforms.",
        "The constant sqrt(2) requires the martingale calculation; scaling alone gives only proportionality.",
        ["laplace-transform", "hitting-times", "scaling"],
        ["durrett_ch7_hitting_time_subordinator", "durrett_ch7_hitting_time_scaling"],
    ),
    piece(
        "reflection_principle",
        "7.4 Path Properties",
        "Reflection principle",
        "theorem",
        "For a>0, P_0(T_a<t)=2 P_0(B_t>=a), where T_a is the first hitting time of level a.",
        "After the first hit of a, reflect the remaining path; rigorously, apply the strong Markov property and symmetry at T_a.",
        "Essential for maxima distributions, hitting-time densities, and barrier-crossing probabilities.",
        "The result is for Brownian motion without drift and with a one-sided level; drift or two-sided barriers need changes.",
        ["reflection-principle", "maximum", "hitting-times"],
        ["durrett_ch7_strong_markov_property"],
    ),
    piece(
        "hitting_time_density",
        "7.4 Path Properties",
        "First hitting-time density",
        "formula",
        "For a>0, T_a has density a (2 pi s^3)^(-1/2) exp(-a^2/(2s)) on s>0.",
        "Differentiate the reflection-principle distribution after a change of variables in the normal tail.",
        "Use for explicit integrals involving first passage times.",
        "This density has heavy tail and infinite mean; do not apply finite-mean intuition.",
        ["hitting-time-density", "reflection-principle", "first-passage"],
        ["durrett_ch7_reflection_principle"],
    ),
    piece(
        "arcsine_last_zero",
        "7.4 Path Properties",
        "Arcsine law for the last zero before one",
        "example-pattern",
        "If L=sup{t<=1:B_t=0}, then P_0(L<=s)=(2/pi) arcsin(sqrt(s)) for 0<s<1.",
        "Condition at time s, use the Markov property and the hitting-time survival probability, then evaluate the integral.",
        "Classic Brownian path distribution and a bridge to random-walk arcsine laws.",
        "The density blows up near 0 and 1; the last zero is not concentrated near 1/2.",
        ["arcsine-law", "last-zero", "path-distribution"],
        ["durrett_ch7_hitting_time_density"],
    ),
    piece(
        "optional_stopping_bounded",
        "7.5 Martingales",
        "Optional stopping for bounded stopping times",
        "theorem",
        "A right-continuous martingale stopped at a bounded stopping time has the same expectation as at time 0.",
        "Approximate the stopping time from above by dyadic times and pass to the limit using right-continuity of the martingale and sigma-fields.",
        "Foundation for Brownian exit probabilities and expected exit times.",
        "Boundedness or another valid stopping hypothesis is required; optional stopping is not automatic for unbounded times.",
        ["optional-stopping", "martingales", "bounded-stopping-time"],
    ),
    piece(
        "brownian_martingale",
        "7.5 Martingales",
        "Brownian motion is a martingale",
        "theorem",
        "B_t is a martingale with respect to the Brownian filtration.",
        "The Markov property gives E_x[B_t|F_s]=E_{B_s}[B_{t-s}]=B_s.",
        "Use with optional stopping to compute two-sided hitting probabilities.",
        "Requires integrability and the correct filtration.",
        ["martingale", "brownian-motion", "markov-property"],
        ["durrett_ch7_markov_property"],
    ),
    piece(
        "two_sided_exit_probability",
        "7.5 Martingales",
        "Two-sided exit probability",
        "formula",
        "For a<x<b, P_x(T_a<T_b)=(b-x)/(b-a).",
        "Stop the martingale B_t at T_a wedge T_b and solve x=a p+b(1-p).",
        "High-yield gambler's-ruin analogue for Brownian motion.",
        "First show or know the exit time is finite; then justify the stopping/localization step.",
        ["exit-probability", "optional-stopping", "gambler-ruin"],
        ["durrett_ch7_brownian_martingale", "durrett_ch7_optional_stopping_bounded"],
    ),
    piece(
        "square_martingale",
        "7.5 Martingales",
        "Square martingale",
        "theorem",
        "B_t^2-t is a martingale.",
        "Expand B_t=B_s+(B_t-B_s), use independence, mean zero, and Var(B_t-B_s)=t-s.",
        "Use to compute expected exit times and quadratic variation intuition.",
        "B_t^2 alone is a submartingale, not a martingale.",
        ["martingale", "quadratic-variation", "second-moment"],
    ),
    piece(
        "expected_interval_exit_time",
        "7.5 Martingales",
        "Expected exit time from an interval",
        "formula",
        "If T=inf{t:B_t notin (a,b)} with a<0<b and B_0=0, then E_0 T=-ab.",
        "Stop B_t^2-t at T wedge t, pass to the limit, and use the exit probabilities to compute E[B_T^2].",
        "Standard computation for Brownian mean exit time from a bounded interval.",
        "Do not confuse exit from (a,b) with hitting a single level; the one-sided hitting time has infinite mean.",
        ["exit-time", "square-martingale", "optional-stopping"],
        ["durrett_ch7_square_martingale", "durrett_ch7_two_sided_exit_probability"],
    ),
    piece(
        "exponential_martingale",
        "7.5 Martingales",
        "Exponential Brownian martingale",
        "theorem",
        "For real theta, exp(theta B_t - theta^2 t/2) is a martingale.",
        "Condition on F_s, factor out exp(theta B_s), and use the normal moment generating function for the independent increment.",
        "Use for Laplace transforms of hitting times and drift/barrier calculations.",
        "The compensator is theta^2 t/2; missing the factor 1/2 breaks the martingale.",
        ["exponential-martingale", "laplace-transform", "gaussian-mgf"],
    ),
    piece(
        "hitting_time_laplace_exact",
        "7.5 Martingales",
        "Exact Laplace transform of a hitting time",
        "formula",
        "For T_a=inf{t:B_t=a} and a>0, E_0 exp(-lambda T_a)=exp(-a sqrt(2 lambda)).",
        "Stop the exponential martingale with theta=sqrt(2 lambda) at T_a wedge t and pass to the limit.",
        "Fastest exact calculation for first-passage Laplace transforms.",
        "The formula is for one-sided hitting from 0 to a>0; signs and starting points need translation.",
        ["hitting-times", "laplace-transform", "exponential-martingale"],
        ["durrett_ch7_exponential_martingale", "durrett_ch7_hitting_time_laplace_shape"],
    ),
    piece(
        "heat_equation_martingales",
        "7.5 Martingales",
        "Heat-equation martingales",
        "theorem",
        "If u_t+(1/2)u_xx=0 for a suitable polynomial u(t,x), then u(t,B_t) is a martingale.",
        "Use Brownian transition densities and the heat equation to show the conditional expectation is unchanged over time.",
        "Generates polynomial martingales such as B_t^3-3tB_t and B_t^4-6tB_t^2+3t^2.",
        "The sign is the backward heat equation sign; check whether the time variable is forward or backward in a problem.",
        ["heat-equation", "polynomial-martingales", "brownian-martingales"],
    ),
    piece(
        "symmetric_exit_second_moment",
        "7.5 Martingales",
        "Second moment of symmetric exit time",
        "formula",
        "For T=inf{t:B_t notin (-a,a)}, E[T^2]=5a^4/3.",
        "Apply optional stopping to the fourth-degree polynomial martingale and combine with E[T]=a^2.",
        "Useful template for computing higher exit-time moments via polynomial martingales.",
        "In nonsymmetric intervals, T and B_T^2 need not be independent, so the same shortcut fails.",
        ["exit-time-moments", "polynomial-martingales", "optional-stopping"],
        ["durrett_ch7_heat_equation_martingales", "durrett_ch7_expected_interval_exit_time"],
    ),
    piece(
        "ito_formula_one_dimensional",
        "7.6 Ito's Formula*",
        "One-dimensional Ito formula",
        "theorem",
        "For f in C^2, f(B_t)-f(B_0)=int_0^t f'(B_s)dB_s + (1/2)int_0^t f''(B_s)ds.",
        "Taylor expand over partitions; first-order terms define the stochastic integral and squared increments converge to elapsed time.",
        "The central calculus rule for functions of Brownian motion.",
        "Ordinary chain rule misses the second-derivative correction.",
        ["ito-formula", "stochastic-calculus", "quadratic-variation"],
        ["durrett_ch7_quadratic_variation_hint"],
    ),
    piece(
        "stochastic_integral_is_martingale",
        "7.6 Ito's Formula*",
        "Stochastic integral martingale criterion",
        "theorem",
        "If g is continuous and E int_0^t |g(B_s)|^2 ds is finite, then int_0^t g(B_s)dB_s is a continuous martingale.",
        "Approximate by adapted step sums, use conditional mean zero and L2 bounds, then pass to limits.",
        "Lets Ito formula immediately produce martingales when the drift term vanishes.",
        "Square-integrability is the hypothesis that keeps the stochastic integral controlled.",
        ["stochastic-integral", "martingale", "square-integrability"],
    ),
    piece(
        "ito_formula_time_space",
        "7.6 Ito's Formula*",
        "Time-space Ito formula",
        "theorem",
        "For f in C^2 in time and space, df(t,B_t)=f_t(t,B_t)dt+f_x(t,B_t)dB_t+(1/2)f_xx(t,B_t)dt.",
        "Apply the one-dimensional formula with an added deterministic time increment and keep only first-order dt plus quadratic Brownian terms.",
        "Use to connect Brownian martingales with PDEs and exponential models.",
        "There is no term involving dt dB_t or (dt)^2 in the limit.",
        ["ito-formula", "pde", "time-space"],
        ["durrett_ch7_ito_formula_one_dimensional"],
    ),
    piece(
        "exponential_brownian_ito",
        "7.6 Ito's Formula*",
        "Ito formula for exponential Brownian motion",
        "example-pattern",
        "For X_t=exp(mu t+sigma B_t), Ito's formula gives dX_t=(mu+sigma^2/2)X_t dt+sigma X_t dB_t.",
        "Differentiate u(t,x)=exp(mu t+sigma x) and insert u_t, u_x, and u_xx into the time-space Ito formula.",
        "Common model pattern for geometric Brownian motion and for checking exponential martingales.",
        "The drift of exp(mu t+sigma B_t) is mu+sigma^2/2, not just mu.",
        ["geometric-brownian-motion", "ito-formula", "exponential"],
        ["durrett_ch7_ito_formula_time_space"],
    ),
    piece(
        "multidimensional_ito_formula",
        "7.6 Ito's Formula*",
        "Multidimensional Ito formula",
        "theorem",
        "For d-dimensional Brownian motion, df(t,B_t)=f_t dt+sum_i f_i dB_t^i+(1/2)sum_i f_{ii} dt.",
        "Second-order Taylor expansion keeps only diagonal quadratic variations; cross terms vanish for independent coordinates.",
        "Use for radial processes, harmonic functions, and multidimensional martingales.",
        "The Laplacian term appears with factor 1/2; mixed second derivatives do not contribute for standard independent Brownian coordinates.",
        ["multidimensional-ito", "laplacian", "brownian-motion"],
        ["durrett_ch7_d_dimensional_brownian", "durrett_ch7_ito_formula_time_space"],
    ),
]


SECTION_GUIDES = [
    {
        "section": "7.1 Definition and Construction",
        "goal": "Define Brownian motion rigorously, construct it, and understand the first layer of path regularity.",
        "must_master": [
            "independent Gaussian increments",
            "Brownian scaling",
            "Gaussian covariance characterization",
            "Kolmogorov continuity criterion",
            "Holder continuity below 1/2",
            "nowhere differentiability",
            "quadratic variation intuition",
        ],
        "prelim_angle": "This section supplies the definitions and scaling heuristics behind nearly every Brownian calculation.",
    },
    {
        "section": "7.2 Markov Property, Blumenthal's 0-1 Law",
        "goal": "Restart Brownian motion at deterministic times and use 0-1 laws for immediate and tail behavior.",
        "must_master": [
            "Markov property",
            "Blumenthal 0-1 law",
            "immediate hitting",
            "time inversion",
            "tail 0-1 law",
            "one-dimensional recurrence",
        ],
        "prelim_angle": "These tools turn qualitative path behavior into short rigorous arguments.",
    },
    {
        "section": "7.3 Stopping Times, Strong Markov Property",
        "goal": "Formalize random times and prove that Brownian motion can be restarted at them.",
        "must_master": [
            "stopping time definitions",
            "hitting times of open and closed sets",
            "F_S",
            "B_S measurability",
            "strong Markov property",
        ],
        "prelim_angle": "Most Brownian hitting-time and reflection-principle problems depend on this section.",
    },
    {
        "section": "7.4 Path Properties",
        "goal": "Use strong Markov arguments to analyze zeros, first passage times, reflection, and arcsine laws.",
        "must_master": [
            "zero set structure",
            "hitting-time increments",
            "hitting-time scaling",
            "reflection principle",
            "first-passage density",
            "arcsine law",
        ],
        "prelim_angle": "This section is the computational core for Brownian maxima and barrier-crossing questions.",
    },
    {
        "section": "7.5 Martingales",
        "goal": "Use Brownian martingales and optional stopping to compute exit probabilities, exit times, and Laplace transforms.",
        "must_master": [
            "optional stopping",
            "B_t martingale",
            "B_t^2-t martingale",
            "exponential martingale",
            "heat-equation martingales",
            "exit-time formulas",
        ],
        "prelim_angle": "The fastest route to most exact Brownian interval and hitting-time computations.",
    },
    {
        "section": "7.6 Ito's Formula*",
        "goal": "Replace ordinary calculus with Ito calculus for Brownian paths and connect stochastic calculus to PDE/martingale methods.",
        "must_master": [
            "one-dimensional Ito formula",
            "stochastic integral martingale property",
            "time-space Ito formula",
            "exponential Brownian motion",
            "multidimensional Ito formula",
        ],
        "prelim_angle": "Even if starred, Ito's formula explains why Brownian martingales and heat equations fit together.",
    },
]


def write_jsonl(path: Path, rows):
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=True) + "\n")


def write_markdown(path: Path):
    lines = [
        "# Durrett Chapter 7 LLM Viki: Brownian Motion",
        "",
        "Source: local extracted PDF `Probability/Textbook/Chapters/PTE-Chapter7.pdf`.",
        "",
        "These are curated study/LLM retrieval pieces, not verbatim textbook notes.",
        "",
        "## Section Guides",
        "",
    ]
    for guide in SECTION_GUIDES:
        lines += [
            f"### {guide['section']}",
            "",
            f"- Goal: {guide['goal']}",
            "",
            f"- Must master: {', '.join(guide['must_master'])}",
            "",
            f"- Prelim angle: {guide['prelim_angle']}",
            "",
        ]
    lines += ["## Knowledge Pieces", ""]
    for row in PIECES:
        lines += [
            f"### {row['title']}",
            "",
            f"- ID: `{row['id']}`",
            "",
            f"- Section: {row['section']}",
            "",
            f"- Kind: {row['kind']}",
            "",
            f"- Summary: {row['summary']}",
            "",
            f"- Proof idea: {row['proof_idea']}",
            "",
            f"- Exam use: {row['exam_use']}",
            "",
            f"- Pitfall: {row['pitfalls']}",
            "",
            f"- Tags: {', '.join(row['tags'])}",
            "",
        ]
        if row["related_ids"]:
            lines += [f"- Related: {', '.join(f'`{rid}`' for rid in row['related_ids'])}", ""]
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_flashcards(path: Path):
    with path.open("w", encoding="utf-8") as f:
        f.write("id\tfront\tback\ttags\n")
        for row in PIECES:
            front = f"Chapter 7: {row['title']}"
            back = f"{row['summary']} Exam use: {row['exam_use']} Pitfall: {row['pitfalls']}"
            tags = ",".join(row["tags"])
            f.write(f"{row['id']}\t{front}\t{back}\t{tags}\n")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    write_jsonl(OUT / "chapter7_knowledge_pieces.jsonl", PIECES)
    write_jsonl(OUT / "chapter7_section_guides.jsonl", SECTION_GUIDES)
    write_markdown(OUT / "chapter7_viki.md")
    write_flashcards(OUT / "chapter7_flashcards.tsv")
    manifest = {
        "name": "durrett_chapter7_brownian_motion_llm_viki",
        "description": "Curated LLM/Viki-style knowledge pieces for Chapter 7 of Durrett Probability: Theory and Examples.",
        "source_file": str(SOURCE),
        "created_at": CREATED,
        "piece_count": len(PIECES),
        "section_count": len(SECTION_GUIDES),
        "files": [
            "chapter7_knowledge_pieces.jsonl",
            "chapter7_section_guides.jsonl",
            "chapter7_viki.md",
            "chapter7_flashcards.tsv",
            "manifest.json",
        ],
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
