from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "Probability/LLM_Viki_Dataset/Chapter3_Knowledge"
SOURCE = ROOT / "Probability/Textbook/Chapters/PTE-Chapter3.pdf"

CREATED = datetime.now(timezone.utc).isoformat()


def piece(pid, section, title, kind, summary, proof_idea, exam_use, pitfalls, tags, related=None):
    return {
        "id": f"durrett_ch3_{pid}",
        "source": "Rick Durrett, Probability: Theory and Examples, extracted Chapter 3 PDF",
        "source_file": str(SOURCE),
        "chapter": 3,
        "section": section,
        "title": title,
        "kind": kind,
        "summary": summary,
        "proof_idea": proof_idea,
        "exam_use": exam_use,
        "pitfalls": pitfalls,
        "tags": tags,
        "related_ids": related or [],
        "created_at": CREATED,
    }


PIECES = [
    piece(
        "stirling_local_binomial",
        "3.1 The De Moivre-Laplace Theorem",
        "Stirling local binomial approximation",
        "formula",
        "For a simple symmetric walk, P(S_{2n}=2k) is asymptotic to (pi n)^(-1/2) exp(-x^2/2) when 2k/sqrt(2n) tends to x.",
        "Insert Stirling's formula into the central binomial coefficient and use (1+c_n)^{a_n} limits.",
        "Use as the prototype local normal approximation before invoking characteristic functions.",
        "The approximation is local and depends on the lattice parity of S_{2n}.",
        ["stirling", "binomial", "local-normal"],
    ),
    piece(
        "demoivre_laplace",
        "3.1 The De Moivre-Laplace Theorem",
        "De Moivre-Laplace theorem",
        "theorem",
        "For a simple symmetric random walk, S_m/sqrt(m) converges in distribution to the standard normal law.",
        "Sum the local binomial approximation over lattice points and identify the resulting Riemann sum with the normal integral.",
        "A concrete CLT model for coin flips, binomial normal approximation, and continuity-correction intuition.",
        "Do not forget the even/odd lattice issue; the theorem for all m follows after a small parity argument.",
        ["clt", "simple-random-walk", "normal-approximation"],
        ["durrett_ch3_stirling_local_binomial"],
    ),
    piece(
        "product_exponential_limit",
        "3.1 The De Moivre-Laplace Theorem",
        "Product exponential limit",
        "lemma",
        "If max_j |c_{j,n}| goes to 0, sum_j c_{j,n} tends to lambda, and the sums of absolute values are bounded, then product_j(1+c_{j,n}) tends to exp(lambda).",
        "Take logarithms, use log(1+x)=x+o(x) uniformly for small x, and control the total error by the absolute-sum bound.",
        "Fast route for birthday, occupancy, and rare-event product limits.",
        "The maximum term condition is essential; a single large factor can break the exponential approximation.",
        ["product-limit", "rare-events", "asymptotics"],
    ),
    piece(
        "large_deviation_stirling_patterns",
        "3.1 The De Moivre-Laplace Theorem",
        "Stirling large-deviation patterns",
        "example-pattern",
        "Stirling's formula also gives exponential rates for binomial and Poisson tails at linear deviations from the mean.",
        "Approximate the largest relevant mass and show nearby tail terms are geometrically controlled.",
        "Useful when an exam asks for n^{-1} log P(S_n >= n a) before the full large-deviation theorem is available.",
        "Normal approximation is not valid on linear-deviation scales; use exponential rates instead.",
        ["large-deviations", "stirling", "tail-asymptotics"],
        ["durrett_ch3_product_exponential_limit"],
    ),
    piece(
        "weak_convergence_definition",
        "3.2 Weak Convergence",
        "Weak convergence definition",
        "definition",
        "Distribution functions F_n converge weakly to F when F_n(x) tends to F(x) at every continuity point of F; random variables converge in distribution when their laws do.",
        "Continuity points are enough because distribution functions are right continuous and have at most countably many jumps.",
        "This is the language used in CLT, Poisson approximation, stable limits, and multivariate limits.",
        "Convergence at discontinuity points of the limit is not required and can fail even for X+1/n tending to X.",
        ["weak-convergence", "distribution-functions", "continuity-points"],
    ),
    piece(
        "rare_geometric_exponential_limit",
        "3.2.1 Examples",
        "Waiting for rare events gives an exponential limit",
        "example-pattern",
        "If X_p is geometric with success probability p, then p X_p converges in distribution to an exponential(1) random variable as p tends to 0.",
        "Use P(p X_p > x)=(1-p)^{floor(x/p)} and the exponential limit lemma.",
        "Recognize geometric waiting times under rare-event scaling.",
        "The scale is p X_p, not X_p/p; the waiting time itself diverges.",
        ["geometric", "exponential-limit", "rare-events"],
        ["durrett_ch3_product_exponential_limit"],
    ),
    piece(
        "birthday_rayleigh_limit",
        "3.2.1 Examples",
        "Birthday collision Rayleigh limit",
        "example-pattern",
        "For iid uniform draws from N boxes, the first collision time T_N satisfies P(T_N/sqrt(N)>x) tending to exp(-x^2/2).",
        "Write the no-collision probability as a product of terms 1-(m-1)/N and apply the product exponential limit.",
        "A standard occupancy/collision scaling pattern.",
        "The natural scale is sqrt(N), not N, because collisions depend on pairs.",
        ["birthday-problem", "occupancy", "rayleigh-tail"],
        ["durrett_ch3_product_exponential_limit"],
    ),
    piece(
        "scheffe_theorem",
        "3.2.1 Examples",
        "Scheffe theorem for densities",
        "theorem",
        "If probability densities f_n converge pointwise to a density f, then the corresponding probability measures converge in total variation, hence weakly.",
        "Use the identity integral |f_n-f| = 2 integral (f-f_n)^+ and dominated convergence.",
        "Use when a limit distribution is easiest to prove through densities, such as central order statistics.",
        "Pointwise convergence of densities is stronger than weak convergence and is not necessary.",
        ["scheffe", "densities", "total-variation"],
    ),
    piece(
        "skorokhod_quantile_representation",
        "3.2.2 Theory",
        "Quantile representation for weak convergence",
        "theorem",
        "If F_n converges weakly to F, one can construct random variables with these laws on (0,1) that converge almost surely.",
        "Use generalized inverse distribution functions and exclude the countable set of flat-level ambiguities.",
        "Lets proof problems transfer weak convergence into almost sure convergence for bounded continuous mappings.",
        "The constructed variables need not be the original variables; this is a representation argument.",
        ["quantile-transform", "skorokhod", "weak-convergence"],
    ),
    piece(
        "bounded_continuous_test_functions",
        "3.2.2 Theory",
        "Bounded continuous test function characterization",
        "theorem",
        "X_n converges in distribution to X iff E g(X_n) tends to E g(X) for every bounded continuous function g.",
        "One direction uses the almost-sure representation and bounded convergence; the converse approximates indicators of half-lines by continuous cutoffs.",
        "The default way to define weak convergence on general topological spaces.",
        "Boundedness matters; unbounded continuous functions need extra tightness or uniform integrability.",
        ["portmanteau", "test-functions", "bounded-continuous"],
        ["durrett_ch3_skorokhod_quantile_representation"],
    ),
    piece(
        "continuous_mapping_theorem",
        "3.2.2 Theory",
        "Continuous mapping theorem",
        "theorem",
        "If X_n converges in distribution to X and g is measurable with P(X in D_g)=0, then g(X_n) converges in distribution to g(X).",
        "Represent X_n and X almost surely, then apply pointwise continuity of g off its discontinuity set.",
        "Use for Slutsky-type transformations, maxima maps, ratios away from zero, and normalization changes.",
        "A discontinuity with positive limit probability can invalidate the conclusion.",
        ["continuous-mapping", "weak-convergence", "discontinuity-set"],
        ["durrett_ch3_bounded_continuous_test_functions"],
    ),
    piece(
        "portmanteau_open_closed",
        "3.2.2 Theory",
        "Portmanteau open-closed criteria",
        "theorem",
        "Weak convergence is equivalent to lower bounds on open sets, upper bounds on closed sets, and convergence on Borel sets whose boundary has limit probability zero.",
        "Use Fatou on indicators after almost-sure representation, then pass between open and closed sets by complements.",
        "Use when events are not intervals but have negligible boundary under the limit.",
        "The direction of the inequalities is easy to reverse; open sets get liminf lower bounds and closed sets get limsup upper bounds.",
        ["portmanteau", "open-sets", "closed-sets"],
        ["durrett_ch3_skorokhod_quantile_representation"],
    ),
    piece(
        "helly_selection_tightness",
        "3.2.2 Theory",
        "Helly selection and tightness",
        "theorem",
        "Every sequence of distribution functions has a vaguely convergent subsequence; subsequential limits are probability laws exactly when mass is tight.",
        "Use a diagonal subsequence over rational points and then repair right continuity; tightness prevents mass escaping to plus or minus infinity.",
        "Core compactness tool for proving existence of subsequential distributional limits.",
        "Vague subsequential limits can lose mass, so Helly alone is not enough for weak convergence.",
        ["helly", "tightness", "subsequences"],
    ),
    piece(
        "moment_tightness_criterion",
        "3.2.2 Theory",
        "Moment tightness criterion",
        "criterion",
        "If sup_n E phi(X_n) is finite for some nonnegative phi with phi(x) tending to infinity as |x| tends to infinity, then the laws of X_n are tight.",
        "Apply Markov's inequality to phi(X_n) outside large compact intervals.",
        "Fast tightness check using bounded moments or coercive Lyapunov functions.",
        "A bounded first or second moment gives tightness, but tightness does not require moments.",
        ["tightness", "markov", "moment-bound"],
        ["durrett_ch3_helly_selection_tightness"],
    ),
    piece(
        "subsequence_principle_weak",
        "3.2.2 Theory",
        "Subsequence principle for weak convergence",
        "proof-template",
        "If every subsequence has a further subsequence converging weakly to the same law, then the full sequence converges weakly to that law.",
        "Use the topological subsequence criterion on real numbers F_n(x) at continuity points.",
        "Useful for proving convergence after compactness/tightness arguments.",
        "The further subsequential limit must be uniquely identified; tightness only gives candidates.",
        ["subsequence", "weak-convergence", "uniqueness"],
    ),
    piece(
        "convergence_in_probability_to_distribution",
        "3.2 Exercises and Consequences",
        "Convergence in probability implies weak convergence",
        "fact",
        "If X_n tends to X in probability, then X_n converges in distribution to X; if X_n converges in distribution to a constant c, then X_n tends to c in probability.",
        "Use inclusions between half-line events with epsilon buffers and continuity points, or use bounded continuous test functions.",
        "Often used to replace negligible error terms in limit theorems.",
        "Weak convergence to a nonconstant random variable does not imply convergence in probability on the original space.",
        ["convergence-in-probability", "weak-convergence", "constant-limit"],
    ),
    piece(
        "converging_together_slutsky",
        "3.2 Exercises and Consequences",
        "Converging together and Slutsky patterns",
        "proof-template",
        "If X_n converges in distribution to X and Y_n converges in distribution to a constant c, then X_n+Y_n, X_n Y_n, and X_n/Y_n (c not 0) converge to the corresponding transformed limits.",
        "Upgrade Y_n to convergence in probability, combine with X_n using tightness and continuous mapping.",
        "Indispensable for replacing random normalizers by deterministic limits.",
        "The denominator case needs the limit constant away from zero.",
        ["slutsky", "converging-together", "random-normalization"],
        ["durrett_ch3_convergence_in_probability_to_distribution", "durrett_ch3_continuous_mapping_theorem"],
    ),
    piece(
        "characteristic_function_definition",
        "3.3.1 Definition, Inversion Formula",
        "Characteristic function basics",
        "definition",
        "The characteristic function of X is phi(t)=E exp(i t X); it is uniformly continuous, positive definite, satisfies phi(0)=1, and determines the distribution.",
        "Most properties follow from bounded convergence and algebra of complex exponentials.",
        "Main transform language for CLT and distributional convergence.",
        "A pointwise limit of characteristic functions is a characteristic function only if it is continuous at zero.",
        ["characteristic-functions", "positive-definite", "transforms"],
    ),
    piece(
        "cf_independent_sums",
        "3.3.1 Definition, Inversion Formula",
        "Characteristic functions multiply for independent sums",
        "theorem",
        "If X and Y are independent, the characteristic function of X+Y is phi_X(t) phi_Y(t).",
        "Factor E exp(i t X) exp(i t Y) by independence.",
        "Turns sums of independent random variables into products and powers of transforms.",
        "The product rule requires independence; uncorrelated variables are not enough.",
        ["independent-sums", "characteristic-functions", "convolution"],
    ),
    piece(
        "standard_characteristic_functions",
        "3.3.1 Definition, Inversion Formula",
        "Standard characteristic function table",
        "example-bank",
        "Coin flip: cos t; Poisson(lambda): exp(lambda(e^{it}-1)); normal(mu,sigma^2): exp(i mu t - sigma^2 t^2/2); uniform(a,b): (e^{itb}-e^{ita})/(it(b-a)); exponential(lambda): lambda/(lambda-it).",
        "Compute directly from sums or integrals, using independence and completing the square for normals.",
        "Recognition table for prelim transform calculations.",
        "Check parameter conventions carefully, especially normal variance and exponential rate versus mean.",
        ["cf-table", "normal", "poisson", "exponential"],
        ["durrett_ch3_characteristic_function_definition"],
    ),
    piece(
        "cf_inversion_formula",
        "3.3.1 Definition, Inversion Formula",
        "Characteristic function inversion formula",
        "theorem",
        "A distribution can be recovered from its characteristic function by integrating (exp(-ita)-exp(-itb))/(it) against phi(t) over symmetric intervals and taking limits at continuity endpoints.",
        "Apply Fubini to the Fourier integral of interval indicators and let the cutoff grow.",
        "Use to prove uniqueness and to identify distributional limits from transforms.",
        "Endpoint atoms require care; inversion is cleanest for intervals whose endpoints have zero mass.",
        ["inversion", "fourier", "uniqueness"],
        ["durrett_ch3_characteristic_function_definition"],
    ),
    piece(
        "integrable_cf_density",
        "3.3.1 Definition, Inversion Formula",
        "Integrable characteristic function gives bounded density",
        "theorem",
        "If a characteristic function is integrable, the distribution has a bounded continuous density given by Fourier inversion.",
        "Use dominated convergence to invert the transform and verify that interval probabilities are integrals of the resulting function.",
        "Shows stable or limiting laws have densities when their characteristic functions are integrable.",
        "Integrability of phi is sufficient, not necessary, for having a density.",
        ["density", "fourier-inversion", "integrable-cf"],
        ["durrett_ch3_cf_inversion_formula"],
    ),
    piece(
        "levy_continuity_theorem",
        "3.3.2 Weak Convergence",
        "Levy continuity theorem",
        "theorem",
        "Probability measures converge weakly iff their characteristic functions converge pointwise to a function continuous at zero, in which case the limit is the characteristic function of the weak limit.",
        "Use tightness plus inversion to identify subsequential limits; continuity at zero prevents mass loss.",
        "The main engine for proving CLT, Poisson limits, stable limits, and multivariate limit theorems.",
        "Pointwise convergence to a discontinuous-at-zero function does not define a probability limit.",
        ["levy-continuity", "weak-convergence", "characteristic-functions"],
        ["durrett_ch3_cf_inversion_formula"],
    ),
    piece(
        "derivatives_moments",
        "3.3.3 Moments and Derivatives",
        "Moments from characteristic function derivatives",
        "theorem",
        "If E|X|^n is finite, then phi has n derivatives and phi^{(k)}(0)=i^k E X^k for k up to n.",
        "Differentiate under the expectation using domination by |X|^k.",
        "Compute moments and build Taylor expansions for CLT proofs.",
        "Existence of a few derivatives at zero can be subtler than finite moments unless the theorem's hypotheses are met.",
        ["moments", "derivatives", "taylor-expansion"],
    ),
    piece(
        "second_order_cf_expansion",
        "3.3.3 Moments and Derivatives",
        "Second-order characteristic function expansion",
        "formula",
        "If EX=0 and EX^2=sigma^2 is finite, then phi(t)=1-sigma^2 t^2/2+o(t^2) as t tends to zero.",
        "Use the Taylor expansion of exp(itX) and dominate the remainder through finite second moment.",
        "This is the one-line input behind the iid CLT by characteristic functions.",
        "The expansion is local near zero; do not apply it at fixed nonzero t without scaling.",
        ["second-moment", "cf-expansion", "clt"],
        ["durrett_ch3_derivatives_moments"],
    ),
    piece(
        "polya_criterion",
        "3.3.4 Polya's Criterion",
        "Polya criterion for characteristic functions",
        "criterion",
        "A real, nonnegative, even, convex-on-positive-rays function with phi(0)=1 and phi(t) tending to 0 at infinity is a characteristic function.",
        "Approximate phi by polygonal functions that are mixtures of triangular characteristic functions and pass to a weak limit.",
        "Useful for constructing stable-law examples such as exp(-|t|^alpha) for 0<alpha<2.",
        "The criterion is sufficient, not necessary; many characteristic functions are not nonnegative or convex.",
        ["polya", "construction", "stable-laws"],
    ),
    piece(
        "moment_problem_carleman",
        "3.3.5 The Moment Problem",
        "Moment problem and Carleman-type uniqueness",
        "theorem",
        "Under suitable growth conditions on even moments, a distribution is determined by its moments.",
        "Use analytic control of the characteristic function or moment generating series near zero.",
        "Helps decide when matching all moments identifies a law.",
        "Moment equality alone is not always enough; lognormal-type examples show nonuniqueness can occur.",
        ["moment-problem", "carleman", "uniqueness"],
    ),
    piece(
        "iid_clt",
        "3.4.1 i.i.d. Sequences",
        "IID central limit theorem",
        "theorem",
        "If X_i are iid with mean mu and variance sigma^2 in (0,infinity), then (S_n-n mu)/(sigma sqrt(n)) converges in distribution to standard normal.",
        "Center and scale, raise the characteristic function at t/sqrt(n) to the nth power, and use the second-order expansion.",
        "The central theorem for normal approximations and asymptotic distribution calculations.",
        "Finite nonzero variance is required for this form; infinite variance can lead to nonnormal stable limits.",
        ["clt", "iid", "normal-limit"],
        ["durrett_ch3_second_order_cf_expansion", "durrett_ch3_levy_continuity_theorem"],
    ),
    piece(
        "normal_approximation_continuity_correction",
        "3.4.1 i.i.d. Sequences",
        "Normal approximation and continuity correction",
        "example-pattern",
        "For binomial or lattice sums, approximate probabilities by normal intervals and shift interval endpoints by half a lattice step for better accuracy.",
        "Apply the CLT to centered and scaled sums while accounting for the discrete histogram cell width.",
        "Useful for coin-flip, dice, roulette, binomial, and Poisson approximations.",
        "The CLT gives large-n accuracy; small tails and lattice endpoints may need correction or sharper bounds.",
        ["normal-approximation", "binomial", "continuity-correction"],
        ["durrett_ch3_iid_clt"],
    ),
    piece(
        "triangular_array_lindeberg_feller",
        "3.4.2 Triangular Arrays",
        "Lindeberg-Feller central limit theorem",
        "theorem",
        "For independent mean-zero triangular arrays with total variance tending to 1, the row sum converges to standard normal iff the Lindeberg condition holds.",
        "Use characteristic functions, compare products with exponentials, and show large terms are negligible exactly under Lindeberg.",
        "The main CLT for non-identically distributed arrays.",
        "The condition is row-wise; do not replace it by iid assumptions unless the array is built that way.",
        ["lindeberg-feller", "triangular-array", "clt"],
        ["durrett_ch3_levy_continuity_theorem"],
    ),
    piece(
        "lyapunov_condition",
        "3.4.2 Triangular Arrays",
        "Lyapunov condition implies Lindeberg",
        "criterion",
        "If a triangular array has normalized (2+delta)-moments whose row sum tends to zero, then the Lindeberg condition holds.",
        "Bound x^2 1{|x|>epsilon} by epsilon^{-delta}|x|^{2+delta}.",
        "Quick sufficient check for triangular-array CLTs.",
        "Lyapunov is stronger than Lindeberg; failure of Lyapunov does not rule out a CLT.",
        ["lyapunov", "lindeberg", "moment-condition"],
        ["durrett_ch3_triangular_array_lindeberg_feller"],
    ),
    piece(
        "random_index_clt",
        "3.4.1 i.i.d. Sequences",
        "Random index CLT",
        "exercise-pattern",
        "If N_t/a(t) tends to 1 in probability and iid centered finite-variance sums satisfy the CLT, then S_{N_t}/sqrt(a(t)) has the same normal limit.",
        "Use maximal inequalities to show the difference between S_{N_t} and S_{a(t)} is negligible on high-probability index windows.",
        "Useful for renewal CLTs and random-sample-size problems.",
        "The random index must be close on the scale needed by the partial-sum fluctuations.",
        ["random-index", "clt", "renewal"],
        ["durrett_ch3_converging_together_slutsky", "durrett_ch3_iid_clt"],
    ),
    piece(
        "erdos_kac",
        "3.4.3 Prime Divisors",
        "Erdos-Kac central limit theorem",
        "theorem",
        "The number of distinct prime divisors of a uniformly chosen integer up to n, after centering and scaling by log log n, converges to the standard normal law.",
        "Approximate divisibility by small primes with nearly independent Bernoulli variables and control the remaining error.",
        "A landmark example where arithmetic statistics obey a CLT.",
        "The variance scale is log log n, not log n.",
        ["erdos-kac", "number-theory", "bernoulli-approximation"],
        ["durrett_ch3_triangular_array_lindeberg_feller"],
    ),
    piece(
        "berry_esseen",
        "3.4.4 Rates of Convergence",
        "Berry-Esseen rate",
        "theorem",
        "For iid centered variables with finite third absolute moment and variance one, the normal approximation error in Kolmogorov distance is O(E|X|^3/sqrt(n)).",
        "Compare characteristic functions through smoothing inequalities and bound the third-order Taylor remainder.",
        "Use when a problem asks for an explicit CLT error rate.",
        "Finite variance alone gives convergence but not this rate.",
        ["berry-esseen", "rates", "kolmogorov-distance"],
    ),
    piece(
        "lattice_span",
        "3.5 Local Limit Theorems",
        "Lattice span from characteristic functions",
        "criterion",
        "For a lattice distribution, the set of t with |phi(t)|=1 encodes the lattice spacing; otherwise |phi(t)|<1 away from zero on compact intervals.",
        "Equality in the triangle inequality forces exp(itX) to be almost surely constant.",
        "Key diagnostic for local limit theorems.",
        "Local limits differ in lattice and nonlattice cases; the span matters.",
        ["lattice", "characteristic-functions", "local-limit"],
    ),
    piece(
        "local_limit_theorem",
        "3.5 Local Limit Theorems",
        "Local limit theorem",
        "theorem",
        "Under suitable lattice hypotheses and finite variance, point probabilities of centered sums are approximated by the normal density times the lattice spacing over sqrt(n).",
        "Use Fourier inversion and split the integral into a small-t CLT region and a large-t region controlled by |phi(t)|<1.",
        "Use when approximating exact probabilities, not just cumulative probabilities.",
        "The ordinary CLT does not imply local probability estimates by itself.",
        ["local-limit", "lattice", "normal-density"],
        ["durrett_ch3_lattice_span", "durrett_ch3_iid_clt"],
    ),
    piece(
        "poisson_triangular_array",
        "3.6.1 The Basic Limit Theorem",
        "Poisson convergence for rare Bernoulli arrays",
        "theorem",
        "For independent Bernoulli variables in row n, if the maximum success probability tends to zero and the sum of success probabilities tends to lambda, then the row sum converges to Poisson(lambda).",
        "Multiply Bernoulli characteristic functions and use log(1+z)=z+o(z) uniformly because all probabilities are small.",
        "The standard law of small numbers for rare-event counts.",
        "The largest individual probability must vanish; total mean convergence alone is not enough.",
        ["poisson-convergence", "law-of-small-numbers", "bernoulli-array"],
        ["durrett_ch3_levy_continuity_theorem"],
    ),
    piece(
        "total_variation_poisson_approximation",
        "3.6.1 The Basic Limit Theorem",
        "Total variation Poisson approximation",
        "theorem",
        "A sum of independent Bernoulli variables is close in total variation to a Poisson variable with matching mean when the sum of squared success probabilities is small.",
        "Compare each Bernoulli law with its Poisson approximation, then use product and convolution contraction inequalities.",
        "Gives quantitative Poisson approximation for rare counts.",
        "Total variation is stronger than weak convergence; the error bound depends on small individual probabilities.",
        ["total-variation", "poisson-approximation", "rare-events"],
        ["durrett_ch3_poisson_triangular_array"],
    ),
    piece(
        "matching_fixed_points",
        "3.6.2 Two Examples with Dependence",
        "Matching fixed points converge to Poisson",
        "example-pattern",
        "The number of fixed points in a uniform random permutation converges to Poisson(1).",
        "Compute factorial moments or use inclusion-exclusion; dependence is weak enough that rare fixed-point events mimic independent Bernoulli events.",
        "Classic dependent rare-event Poisson limit.",
        "The indicators are not independent, so the basic Bernoulli-array theorem does not apply directly.",
        ["matching", "fixed-points", "poisson-limit"],
    ),
    piece(
        "occupancy_empty_boxes",
        "3.6.2 Two Examples with Dependence",
        "Occupancy empty-box Poisson limit",
        "example-pattern",
        "When r balls are thrown into n boxes and n exp(-r/n) tends to lambda, the number of empty boxes converges to Poisson(lambda).",
        "Use inclusion-exclusion or Poissonization to handle dependence among empty-box indicators.",
        "Appears in coupon collector and hashing problems.",
        "Empty-box events are dependent; independence heuristics need justification.",
        ["occupancy", "empty-boxes", "poisson-limit"],
        ["durrett_ch3_poisson_triangular_array"],
    ),
    piece(
        "poisson_process_increments",
        "3.7 Poisson Processes",
        "Poisson process from independent increments",
        "theorem",
        "A counting process with stationary independent increments, no multiple jumps in small intervals, and jump probability asymptotic to lambda h has N(0,t) distributed as Poisson(lambda t).",
        "Partition [0,t] into many small intervals and apply Poisson convergence to the rare jump indicators.",
        "Foundation for continuous-time rare-event models.",
        "The small-interval multiple-jump condition is needed to reduce counts to Bernoulli indicators.",
        ["poisson-process", "independent-increments", "counting-process"],
        ["durrett_ch3_poisson_triangular_array"],
    ),
    piece(
        "compound_poisson",
        "3.7.1 Compound Poisson Processes",
        "Compound Poisson process",
        "construction",
        "If N is a Poisson process and Y_i are iid jumps independent of N, then sum_{i<=N(t)} Y_i is a compound Poisson process with characteristic function exp(lambda t (E exp(i theta Y)-1)).",
        "Condition on N(t) and use the iid product rule for characteristic functions.",
        "Models random sums and jump processes with nonunit jump sizes.",
        "Do not confuse the rate of arrivals with the distribution of jump sizes.",
        ["compound-poisson", "random-sum", "jump-process"],
        ["durrett_ch3_cf_independent_sums"],
    ),
    piece(
        "poisson_thinning",
        "3.7.2 Thinning",
        "Thinning of a Poisson process",
        "theorem",
        "If each point of a rate lambda Poisson process is independently assigned a type j with probability p_j, then the type-specific counting processes are independent Poisson processes with rates lambda p_j.",
        "Condition on the total count, use multinomial splitting, and identify the joint generating or characteristic function.",
        "Use for marked processes, occupancy via Poissonization, and splitting arrivals into classes.",
        "Independence of the marks is essential for independent thinned processes.",
        ["thinning", "marked-poisson", "independent-poisson"],
        ["durrett_ch3_poisson_process_increments"],
    ),
    piece(
        "poisson_order_statistics",
        "3.7.3 Conditioning",
        "Poisson arrivals conditional on count are order statistics",
        "theorem",
        "Given N(t)=n in a homogeneous Poisson process, the arrival times in [0,t] have the same joint distribution as the order statistics of n iid uniform(0,t) variables.",
        "Use the joint density of exponential interarrival times restricted to total arrival time below t and no next arrival before t.",
        "Turns Poisson-process conditioning questions into uniform order-statistic problems.",
        "This is conditional on the count; unconditionally the arrival times are not a fixed-size sample.",
        ["poisson-process", "conditioning", "order-statistics"],
    ),
    piece(
        "stable_law_domain_attraction",
        "3.8 Stable Laws",
        "Stable law domain of attraction",
        "theorem",
        "Heavy-tailed iid sums with regularly varying tails of index alpha in (0,2) converge after n^{1/alpha}-type scaling and suitable centering to an alpha-stable law.",
        "Use triangular-array convergence of small jumps plus Poisson behavior of large jumps encoded through characteristic functions.",
        "Explains nonnormal limits when variance is infinite.",
        "Centering depends on alpha and tail balance; do not reuse finite-variance CLT normalization.",
        ["stable-laws", "heavy-tails", "domain-of-attraction"],
        ["durrett_ch3_levy_continuity_theorem"],
    ),
    piece(
        "stable_characteristic_exponent",
        "3.8 Stable Laws",
        "Stable characteristic exponent",
        "formula",
        "Stable laws have characteristic functions with exponent governed by alpha, scale, skewness, and centering parameters; symmetric stable laws have exp(-c |t|^alpha).",
        "Derive from the limiting Levy measure or from the scaling property of sums.",
        "Recognition tool for identifying stable limits from characteristic functions.",
        "The alpha=1 case has special logarithmic centering behavior in nonsymmetric cases.",
        ["stable-laws", "characteristic-functions", "heavy-tails"],
        ["durrett_ch3_stable_law_domain_attraction"],
    ),
    piece(
        "convergence_of_types",
        "3.8 Stable Laws",
        "Convergence of types theorem",
        "theorem",
        "If a_n X_n+b_n converges to a nondegenerate limit and c_n X_n+d_n converges to another nondegenerate limit, then c_n/a_n and d_n-b_n c_n/a_n have limits linking the two laws by affine transformation.",
        "Use tightness and uniqueness of subsequential affine normalizations.",
        "Useful for proving uniqueness of scaling and centering in stable-limit problems.",
        "The limit must be nondegenerate; constants allow pathological normalization changes.",
        ["convergence-of-types", "normalization", "stable-laws"],
    ),
    piece(
        "infinitely_divisible_definition",
        "3.9 Infinitely Divisible Distributions",
        "Infinitely divisible distributions",
        "definition",
        "A distribution is infinitely divisible if for every n it can be represented as the law of a sum of n iid random variables.",
        "Limits of row sums of infinitesimal triangular arrays have this divisibility because each row can be split into many small independent pieces.",
        "Normal, Poisson, compound Poisson, and stable laws are key examples.",
        "Not every distribution is infinitely divisible; bounded nonconstant laws are not.",
        ["infinitely-divisible", "triangular-arrays", "limit-laws"],
    ),
    piece(
        "levy_khinchin",
        "3.9 Infinitely Divisible Distributions",
        "Levy-Khinchin representation",
        "theorem",
        "Characteristic functions of infinitely divisible laws have an exponent decomposed into drift, Gaussian variance, and an integral term governed by a Levy measure.",
        "Analyze limits of triangular-array characteristic exponents and separate small Gaussian fluctuations from jumps.",
        "The master formula unifying normal, Poisson, compound Poisson, and stable laws.",
        "The Levy measure is not a probability measure; it controls jump intensity and must satisfy an integrability condition near zero.",
        ["levy-khinchin", "infinitely-divisible", "levy-measure"],
        ["durrett_ch3_infinitely_divisible_definition"],
    ),
    piece(
        "multivariate_weak_convergence",
        "3.10 Limit Theorems in R^d",
        "Multivariate weak convergence",
        "definition",
        "Weak convergence in R^d can be defined through bounded continuous test functions, rectangle distribution functions at continuity points, or probability convergence on continuity sets.",
        "Extend one-dimensional portmanteau and tightness arguments using rectangles that generate the Borel sigma-field.",
        "Needed for joint convergence, random vectors, and multivariate CLT.",
        "Coordinatewise convergence alone does not imply joint convergence unless dependence is controlled.",
        ["multivariate", "weak-convergence", "random-vectors"],
        ["durrett_ch3_bounded_continuous_test_functions", "durrett_ch3_portmanteau_open_closed"],
    ),
    piece(
        "multivariate_cf_convergence",
        "3.10 Limit Theorems in R^d",
        "Multivariate characteristic function convergence",
        "theorem",
        "Random vectors converge in distribution iff their multivariate characteristic functions converge pointwise to a function continuous at the origin.",
        "Use multidimensional inversion and tightness, paralleling the one-dimensional Levy continuity theorem.",
        "Primary method for proving joint limit theorems.",
        "Checking only marginal characteristic functions misses dependence; the full vector transform is needed.",
        ["multivariate-cf", "levy-continuity", "joint-convergence"],
        ["durrett_ch3_levy_continuity_theorem"],
    ),
    piece(
        "cramer_wold",
        "3.10 Limit Theorems in R^d",
        "Cramer-Wold device",
        "theorem",
        "A sufficient and standard condition for X_n in R^d to converge to X is that theta dot X_n converges in distribution to theta dot X for every theta in R^d.",
        "Linear projections determine the multivariate characteristic function by phi_X(theta)=E exp(i theta dot X).",
        "Turns multivariate convergence into one-dimensional convergence problems.",
        "All directions theta are needed; finitely many coordinate projections are not enough.",
        ["cramer-wold", "projections", "joint-convergence"],
        ["durrett_ch3_multivariate_cf_convergence"],
    ),
    piece(
        "multivariate_clt",
        "3.10 Limit Theorems in R^d",
        "Central limit theorem in R^d",
        "theorem",
        "For iid random vectors with mean vector m and covariance matrix Sigma, n^{-1/2} sum (X_i-m) converges to a multivariate normal with covariance Sigma.",
        "Apply the one-dimensional CLT to theta dot X_i for every theta and then use Cramer-Wold.",
        "Use for joint asymptotic normality and random-walk scaling in higher dimensions.",
        "A singular covariance matrix still gives a valid degenerate multivariate normal limit.",
        ["multivariate-clt", "normal-vector", "covariance"],
        ["durrett_ch3_cramer_wold", "durrett_ch3_iid_clt"],
    ),
]


SECTION_GUIDES = [
    {
        "section": "3.1 The De Moivre-Laplace Theorem",
        "study_goal": "Understand the normal limit first through exact binomial probabilities and Stirling asymptotics.",
        "must_master": ["Stirling formula", "local binomial approximation", "Riemann-sum normal limit", "linear-deviation contrast"],
        "prelim_angle": "A concrete way to derive normal approximation and avoid using the CLT as a black box.",
    },
    {
        "section": "3.2 Weak Convergence",
        "study_goal": "Use distributional convergence through continuity points, test functions, mapping theorems, and tightness.",
        "must_master": ["weak convergence definition", "Portmanteau theorem", "continuous mapping", "tightness", "Helly selection", "Slutsky patterns"],
        "prelim_angle": "Most limit-theorem problems need these tools to move from transforms to events or transformed variables.",
    },
    {
        "section": "3.3 Characteristic Functions",
        "study_goal": "Use Fourier transforms to identify laws, prove weak convergence, and extract moment expansions.",
        "must_master": ["characteristic functions", "inversion", "Levy continuity theorem", "moment derivatives", "standard transform table"],
        "prelim_angle": "High-yield method for CLT, Poisson convergence, random sums, and independence checks.",
    },
    {
        "section": "3.4 Central Limit Theorems",
        "study_goal": "Prove normal limits for iid sequences and triangular arrays, and recognize rate and arithmetic examples.",
        "must_master": ["iid CLT", "Lindeberg-Feller", "Lyapunov condition", "random index CLT", "Berry-Esseen"],
        "prelim_angle": "The central computation theme of Chapter 3; many exam problems are variants with changed normalization or dependence.",
    },
    {
        "section": "3.5 Local Limit Theorems",
        "study_goal": "Upgrade cumulative CLT statements to point-probability approximations using Fourier inversion.",
        "must_master": ["lattice span", "local normal approximation", "small-t/large-t split"],
        "prelim_angle": "Useful when the problem asks for exact mass asymptotics instead of only distributional convergence.",
    },
    {
        "section": "3.6 Poisson Convergence",
        "study_goal": "Recognize and prove laws of small numbers for rare-event counts, with and without dependence.",
        "must_master": ["Bernoulli array theorem", "total variation approximation", "matching", "occupancy"],
        "prelim_angle": "Common source of limit-distribution questions where the limit is Poisson rather than normal.",
    },
    {
        "section": "3.7 Poisson Processes",
        "study_goal": "Move from rare-event counts to continuous-time counting processes, thinning, compounding, and conditioning.",
        "must_master": ["independent increments", "compound Poisson", "thinning", "conditional order statistics"],
        "prelim_angle": "Connects Chapter 3 convergence tools with stochastic-process modeling.",
    },
    {
        "section": "3.8 Stable Laws",
        "study_goal": "Understand nonnormal limits for heavy-tailed sums and the role of scaling, skewness, and centering.",
        "must_master": ["stable characteristic functions", "domain of attraction", "regular variation", "convergence of types"],
        "prelim_angle": "A warning system for infinite-variance problems where sqrt(n) normalization is wrong.",
    },
    {
        "section": "3.9 Infinitely Divisible Distributions",
        "study_goal": "See normal, Poisson, compound Poisson, and stable laws as members of one triangular-array limit family.",
        "must_master": ["infinite divisibility", "Levy-Khinchin formula", "Levy measure", "Gaussian and jump components"],
        "prelim_angle": "Less often computational, but excellent for recognizing possible limits of infinitesimal arrays.",
    },
    {
        "section": "3.10 Limit Theorems in R^d",
        "study_goal": "Extend weak convergence, characteristic functions, and CLT arguments to random vectors.",
        "must_master": ["multivariate weak convergence", "multivariate characteristic functions", "Cramer-Wold", "multivariate CLT"],
        "prelim_angle": "Joint convergence questions usually reduce to projections and covariance calculations.",
    },
]


def write_jsonl(path: Path, rows):
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def main():
    OUT.mkdir(parents=True, exist_ok=True)

    write_jsonl(OUT / "chapter3_knowledge_pieces.jsonl", PIECES)
    write_jsonl(OUT / "chapter3_section_guides.jsonl", SECTION_GUIDES)

    manifest = {
        "name": "durrett_chapter3_central_limit_theorems_llm_viki",
        "description": "Curated LLM/Viki-style knowledge pieces for Chapter 3 of Durrett Probability: Theory and Examples.",
        "source_file": str(SOURCE),
        "created_at": CREATED,
        "piece_count": len(PIECES),
        "section_count": len(SECTION_GUIDES),
        "files": [
            "chapter3_knowledge_pieces.jsonl",
            "chapter3_section_guides.jsonl",
            "chapter3_viki.md",
            "chapter3_flashcards.tsv",
            "manifest.json",
        ],
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    md = ["# Durrett Chapter 3 LLM Viki: Central Limit Theorems\n"]
    md.append("Source: local extracted PDF `Probability/Textbook/Chapters/PTE-Chapter3.pdf`.\n")
    md.append("These are curated study/LLM retrieval pieces, not verbatim textbook notes.\n")
    md.append("## Section Guides\n")
    for guide in SECTION_GUIDES:
        md.append(f"### {guide['section']}\n")
        md.append(f"- Goal: {guide['study_goal']}\n")
        md.append(f"- Must master: {', '.join(guide['must_master'])}\n")
        md.append(f"- Prelim angle: {guide['prelim_angle']}\n")
    md.append("## Knowledge Pieces\n")
    for item in PIECES:
        md.append(f"### {item['title']}\n")
        md.append(f"- ID: `{item['id']}`\n")
        md.append(f"- Section: {item['section']}\n")
        md.append(f"- Kind: {item['kind']}\n")
        md.append(f"- Summary: {item['summary']}\n")
        md.append(f"- Proof idea: {item['proof_idea']}\n")
        md.append(f"- Exam use: {item['exam_use']}\n")
        md.append(f"- Pitfall: {item['pitfalls']}\n")
        md.append(f"- Tags: {', '.join(item['tags'])}\n")
    (OUT / "chapter3_viki.md").write_text("\n".join(md), encoding="utf-8")

    flash = ["id\tfront\tback\ttags"]
    for item in PIECES:
        front = f"{item['title']} ({item['section']})"
        back = f"{item['summary']} Exam use: {item['exam_use']} Pitfall: {item['pitfalls']}"
        flash.append(f"{item['id']}\t{front}\t{back}\t{','.join(item['tags'])}")
    (OUT / "chapter3_flashcards.tsv").write_text("\n".join(flash) + "\n", encoding="utf-8")

    print(json.dumps(manifest, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
